### ISSUE TITLE
Errore in ricerca pendenze o pagamenti per CF/PIVA

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#213]
**Descrizione del Bug**
Ricercando nelle pendenze per codice fiscale si ottiene un errore interno. Inserendo invece una p.iva nella ricerca per pagamenti o pendenze il pulsante di ricerca non si abilita.

**Come riprodurlo:**
Se si ricerca una pendenza per codice fiscale, si ottiene un NPE:

```
2020-06-24 10:36:20.486 | ERROR | it.govpay.backoffice.v1.controllers.BaseController:165 | 6bd12ddb-1305-4388-aa4c-2272b7c5d2d5 | Errore interno durante findPendenze: null
java.lang.NullPointerException
        at it.govpay.bd.pagamento.filters.VersamentoFilter.getParameters(VersamentoFilter.java:763) ~[orm-3.3.0-SNAPSHOT.jar:?]
        at it.govpay.bd.pagamento.VersamentiBD.count(VersamentiBD.java:353) ~[orm-3.3.0-SNAPSHOT.jar:?]
        at it.govpay.core.dao.pagamenti.PendenzeDAO.listaPendenze(PendenzeDAO.java:309) ~[core-3.3.0-SNAPSHOT.jar:?]
        at it.govpay.core.dao.pagamenti.PendenzeDAO.listaPendenze(PendenzeDAO.java:221) ~[core-3.3.0-SNAPSHOT.jar:?]
        at it.govpay.backoffice.v1.controllers.PendenzeController.findPendenze(PendenzeController.java:296) ~[classes:?]
        at it.govpay.backoffice.v1.Pendenze.findPendenze(Pendenze.java:53) ~[classes:?]
```

Se si inserisce nella ricerca una partita iva nei box di ricerca di pagamenti o pedenze, la ricerca non viene abilitata.

Se si riduce la finestra, il box di ricerca laterale sparisce e compare una ricerca testuale non prevista. Il box dovrebbe essere renderizzato in testa alla pagina, eventualmente nascosto con possibilita' di mostrarlo/nasconderlo con il pulsante della lente.

**Screenshots:**
![Schermata da 2020-06-24 10-43-17](https://user-images.githubusercontent.com/12340738/85523723-a0fa3580-b607-11ea-87b4-df2da26f7ba8.png)
![Schermata da 2020-06-24 10-42-52](https://user-images.githubusercontent.com/12340738/85523754-a788ad00-b607-11ea-917c-f8eabf0af5da.png)

**Comment by nardil** [comment]
Modificare il suggerimento per riportare `Cod. Fiscale/P. IVA`
