### ISSUE TITLE
NPE in fase di produzione pdf con jasperreports

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#242]
**Descrizione:**
In alcuni ambienti linux si verifica un NPE in fase di produzione PDF
```
net.sf.jasperreports.engine.JRRuntimeException: Error initializing graphic environment.
        at net.sf.jasperreports.engine.util.JRGraphEnvInitializer.initializeGraphEnv(JRGraphEnvInitializer.java:63) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.BaseReportFiller.<init>(BaseReportFiller.java:122) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRBaseFiller.<init>(JRBaseFiller.java:244) ~[jasperreports-6.2.2.jar:6.2.2]
....
Caused by: java.lang.NullPointerException
        at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264) ~[?:1.8.0_252]
        at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219) ~[?:1.8.0_252]
        at sun.awt.FontConfiguration.init(FontConfiguration.java:107) ~[?:1.8.0_252]
````

Come indicato in [questa issue](https://github.com/AdoptOpenJDK/openjdk-docker/issues/75) il problema e' riconducibile alla configurazione del sistema.

Si risolve istallando i pacchetti `fontconfig` and `urw-fonts`.

**Documentazione:**
Aggiungere alle informazioni preliminari la dipendenza da questi due pacchetti in ambiente linux

**Comment by nardil** [comment]
Aggiunta anche questa property JVM: `java.awt.headless=true`
