### ISSUE TITLE
Inizializzazione di GovPay Console fallita

### ISSUE THREAD

**Issue by stasbranger** [link-it/GovPay#29]
Salve, 

sto provando a far partire il progetto seguendo la guida di installazione ma all'esecuzione di jboss 7.1.1 ho il seguente errore. Qualcuno mi sa dare una mano?

`10:27:07,087 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/govpayConsole]] (MSC service thread 1-2) Exception sending context initialized event to listener instance of class it.govpay.web.InitListener: java.lang.RuntimeException: Inizializzazione di GovPay Console fallita: org.openspcoop2.utils.UtilsException: Lookup jndiResource [java:/govpay] failed: Error looking up govpay, service service jboss.naming.context.java.govpay is not started
	at it.govpay.web.InitListener.contextInitialized(InitListener.java:63) [classes:]
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3392) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3850) [jbossweb-7.0.13.Final.jar:]
	at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:90) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]
Caused by: org.openspcoop2.utils.UtilsException: Lookup jndiResource [java:/govpay] failed: Error looking up govpay, service service jboss.naming.context.java.govpay is not started
	at org.openspcoop2.utils.datasource.DataSourceFactory.newInstance(DataSourceFactory.java:121) [openspcoop2_utils-2.3.5.jar:]
	at it.govpay.bd.ConnectionManager.initialize(ConnectionManager.java:65) [govpay-orm-2.2.5.jar:]
	at it.govpay.web.InitListener.contextInitialized(InitListener.java:61) [classes:]
	... 8 more
Caused by: javax.naming.NameNotFoundException: Error looking up govpay, service service jboss.naming.context.java.govpay is not started
	at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:126)
	at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:74)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:178)
	at org.jboss.as.naming.InitialContext.lookup(InitialContext.java:113)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:214)
	at javax.naming.InitialContext.lookup(InitialContext.java:411) [rt.jar:1.7.0_80]
	at org.openspcoop2.utils.resources.GestoreJNDI.lookup(GestoreJNDI.java:79) [openspcoop2_utils-2.3.5.jar:]
	at org.openspcoop2.utils.datasource.DataSourceFactory.newInstance(DataSourceFactory.java:119) [openspcoop2_utils-2.3.5.jar:]
	... 10 more
`

**Comment by nardil** [comment]
Dall'errore sembrerebbe che non è stato correttamente deployato il datasource necessario alla GovPay Console.  Dovresti verificare dai log di avvio di JBoss lo stato di deploy, magari avviandolo con il solo datasource da deployare in modo da individuare più facilmente la parte di tuo interesse.

**Comment by nardil** [comment]
Issue chiuso per errore.

**Comment by nardil** [comment]
@stasbranger Issue chiusa per inattivita'. In caso fosse ancora un problema aperto, riaprilo pure
