### ISSUE TITLE
Errore nella finalizzazione del Pagamento su GovPay

### ISSUE THREAD

**Issue by frdidonato** [link-it/govpay#311]
Salve, sto effettuando i test per l'accreditamento e riesco ad effettuare un pagamento con successo. Alla chiusura della finestra del wisp ricevo anche la ricevuta del pagamento sulla mail da PagoPa. 
Se però provo a scaricare la ricevuta da govpay tramite le api, mi viene restituito un errore di Risorsa non Trovata, e il pagamento risulta sempre in stato "Pagamento in corso".
Sul log di GovPay, ogni tanto, vedo questo errore
`2021-04-12 13:00:01.414 | INFO  | it.govpay.core.business.Pagamento:160 | c9065dd2-c983-4410-aa52-0fbec2f42d49 | Rpt pendente su GovPay [Dominio:----IUV:00000000000040233 CCP:120420211217661026]: stato RPT_ACCETTATA_NODO
2021-04-12 13:00:01.414 | INFO  | it.govpay.core.business.Pagamento:176 | c9065dd2-c983-4410-aa52-0fbec2f42d49 | Rpt non pendente o sconosciuta sul nodo [Dominio:-----IUV:00000000000040233 CCP:120420211217661026]
2021-04-12 13:00:01.414 | INFO  | it.govpay.core.utils.RptUtils:251 | c9065dd2-c983-4410-aa52-0fbec2f42d49 | Rpt [Dominio:----- IUV:00000000000040233 CCP:120420211217661026] in stato non terminale [RPT_ACCETTATA_NODO]. Eseguo un aggiornamento dello stato con il Nodo dei Pagamenti.
2021-04-12 13:00:01.414 | WARN  | it.govpay.core.business.Pagamento:188 | c9065dd2-c983-4410-aa52-0fbec2f42d49 | Errore durante l'aggiornamento della RPT

java.lang.NullPointerException
        at it.govpay.core.utils.RptUtils.aggiornaRptDaNpD(RptUtils.java:272) ~[core-3.3.1.jar:?]
        at it.govpay.core.business.Pagamento.verificaTransazioniPendenti(Pagamento.java:181) [core-3.3.1.jar:?]
        at it.govpay.core.business.Operazioni.recuperoRptPendenti(Operazioni.java:187) [core-3.3.1.jar:?]
        at it.govpay.core.utils.tasks.RecuperoRptPendenti.execTask(RecuperoRptPendenti.java:16) [core-3.3.1.jar:?]
        at it.govpay.core.utils.tasks.AbstractTask.exec(AbstractTask.java:38) [core-3.3.1.jar:?]
        at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0]
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) [spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0]
`
Sapreste dirmi in quale punto la comunicazione con pagopa non va a buon fine ? sembra ci sia un problema solamente nella comunicazione/aggiornamento dello stato del pagamento e non riesco a capire se si tratti di un problema di configurazione.

**Comment by nardil** [comment]
Ciao @frdidonato ,

la transazione si trova in stato "Pagamento in corso" perche' la piattaforma non ha ricevuto la RT da pagoPA che attesta l'esito del pagamento, pertanto la prima verifica da fare e' se questa comunicazione e' mai arrivata e se e' stata acquisita correttamente tramite il Giornale degli Eventi.

I log individuati sono generati dai processi di recupero di GovPay che tentano di sanare la situazione recuperando la ricevuta, ma risulta in eccezione. L'errore da te segnalato non mi risulta pero' possibile se non modificando manualmente la base dati. Hai per caso fatto operazioni di questo tipo?

Eventualmente dovresti riportare il risultato di queste interrogazioni per accertarsene:

```sql
SELECT id_versamento FROM rpt 
WHERE iuv='00000000000040233' AND ccp='120420211217661026'

SELECT id_applicazione FROM versamenti
JOIN rpt ON rpt.id_versamento=versamenti.id
WHERE iuv='00000000000040233' AND ccp='120420211217661026'

SELECT cod_applicazione FROM applicazioni 
JOIN versamenti ON applicazioni.id=versamenti.id_applicazione
JOIN rpt ON rpt.id_versamento=versamenti.id
WHERE iuv='00000000000040233' AND ccp='120420211217661026'
```

**Comment by frdidonato** [comment]
Ciao @nardil e grazie, come sempre, del sollecito supporto.
In allegato il log degli eventi relativo ad uno di questi pagamenti che non riesco a finalizzare
![log_eventi](https://user-images.githubusercontent.com/81362592/114400132-f3f6a680-9ba1-11eb-84b9-86bc17758a37.png)

Riguardo alla questione delle modifiche sul db qualche giorno fa ho tantato di scatenare alcune primitive seguendo questa issue 
https://github.com/link-it/govpay/issues/180#issuecomment-598801045
Non vorrei aver fatto qualche update che mi abbia portato a questa situazione di inconsistenza.
Di seguito il risultato delle query che mi hai chiesto

`SELECT id_versamento FROM rpt 
WHERE iuv='00000000000040233' AND ccp='120420211217661026'`

id_versamento = 12

`SELECT id_applicazione FROM versamenti
JOIN rpt ON rpt.id_versamento=versamenti.id
WHERE iuv='00000000000040233' AND ccp='120420211217661026'`

id_applicazione=1

`SELECT cod_applicazione FROM applicazioni 
JOIN versamenti ON applicazioni.id=versamenti.id_applicazione
JOIN rpt ON rpt.id_versamento=versamenti.id
WHERE iuv='00000000000040233' AND ccp='120420211217661026'`

cod_applicazione = publisysapi

**Comment by nardil** [comment]
Non mi ero accorto che era una versione non aggiornata. Dovresti aggiornare all'ultima versione rilasciata dove e' gia' presente il fix da te individuato (per questo non capivo l'errore)

https://github.com/link-it/govpay/blob/6035f661e38cddc3b817d55bd0d7641d12da292d/jars/core/src/main/java/it/govpay/core/utils/RptUtils.java#L272
