### ISSUE TITLE
NPE autorizzazione servizi CCP e RT

### ISSUE THREAD

**Issue by nardil** [link-it/govpay#340]
In presenza di mancata di autenticazione (da chiarire la configurazione che "passa" spring security ma non si e' autenticati) si dovrebbe avere un errore di autorizzazione, ma invece si ha un NPE.

```
Caused by: java.lang.NullPointerException
	at it.govpay.core.autorizzazione.AuthorizationManager.checkPrincipal(AuthorizationManager.java:40) ~[core-3.4.0.jar:?]
	at it.govpay.web.ws.PagamentiTelematiciRTImpl.paaInviaRT(PagamentiTelematiciRTImpl.java:298) ~[classes:?]
	... 101 more
```

**Comment by nardil** [comment]
Segnalato in #338

**Comment by MatteoT9890** [comment]
Ecco la configurazione SpringSecurity. Con alta probabilità è la clausola `permitAll` anzichè `isFullyAuthenticated` a causa la NPE.

```
 <!-- BASIC_START -->
        <b:bean id="basicAuthenticationEntryPoint" class="it.govpay.rs.v1.authentication.entrypoint.BasicAuthenticationEntryPoint" >
        <b:property name="wwwAuthenticate" value="false"/>
        </b:bean>

        <b:bean id="userDetailServiceUtenze" class="it.govpay.core.dao.autorizzazione.AutenticazioneUtenzeAnonimeDAO" >
                <b:property name="apiName" value="API_PAGOPA" />
                <b:property name="authType" value="BASIC" />
        </b:bean>

        <b:bean id="wildflyApplicationAuthenticationProvider" class="org.openspcoop2.utils.service.authentication.provider.WildflyApplication$
                        <b:property name="userDetailsService" ref="userDetailServiceUtenze"/>
                </b:bean>

        <authentication-manager id="authenticationManager">
                <authentication-provider ref="wildflyApplicationAuthenticationProvider">
                </authentication-provider>
        </authentication-manager>

        <http auto-config="false" use-expressions="true" create-session="stateless" authentication-manager-ref="authenticationManager">

                <csrf disabled="true"/>

                <intercept-url pattern="*?wsdl" access="permitAll" />
                <intercept-url pattern="/**" access="isFullyAuthenticated()" />

                <http-basic entry-point-ref="basicAuthenticationEntryPoint" />
                <headers>
                        <content-type-options disabled="true"/>
                        <frame-options disabled="true"/>
                        <xss-protection disabled="true"/>
                </headers>
        </http>
```
