### ISSUE TITLE
Avvio ed errori deploy

### ISSUE THREAD

**Issue by pievealessandro** [link-it/GovPay#37]
Salve,
stavo provando ad eseguire il manuale di installazione di GovPay con questi requisiti:
- java version "1.8.0_131"
- Mysql
- JBoss71.1.Final

Eseguo l'installer senza errori, e la fase di dispiegamento (fase 4 sul manuale)
- copio govpay.ear dentro la cartella deployments 
- copio govpayConsole.war dentro la cartella deployments 
- modifico il file govpay-ds.xml con <driver>mysql-connector-java-5.1.42-bin.jar</driver> (jar copiato dentro la cartella deployments

In avvio di Jboss  ricevo errori e non si avvia 
l'ultimo errore da console segnalato è:
```
10:55:44,965 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-3) MSC00001: Failed to start service jboss.deployment.subunit."govpay.ear"."govpay-web-2.3.3.0.war".component.StartupEjb.START: org.jboss.msc.service.StartException in service jboss.deployment.subunit."govpay.ear"."govpay-web-2.3.3.0.war".component.StartupEjb.START: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1767) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]
Caused by: java.lang.IllegalStateException: JBAS011048: Failed to construct component instance
	at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:163)
	at org.jboss.as.ee.component.BasicComponent.createInstance(BasicComponent.java:85)
	at org.jboss.as.ejb3.component.singleton.SingletonComponent.getComponentInstance(SingletonComponent.java:116)
	at org.jboss.as.ejb3.component.singleton.SingletonComponent.start(SingletonComponent.java:130)
	at org.jboss.as.ee.component.ComponentStartService.start(ComponentStartService.java:44)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	... 3 more
Caused by: javax.ejb.EJBException: java.lang.RuntimeException: Inizializzazione di GovPay fallita: java.lang.Exception: Il path indicato nella property "it.govpay.batch.estrattoConto.pathEsportazione" (/var/govpay/estrattoConto) non esiste o non e' un folder.
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.handleExceptionInOurTx(CMTTxInterceptor.java:166)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:230)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.requiresNew(CMTTxInterceptor.java:333)
	at org.jboss.as.ejb3.tx.SingletonLifecycleCMTTxInterceptor.processInvocation(SingletonLifecycleCMTTxInterceptor.java:56)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ee.component.TCCLInterceptor.processInvocation(TCCLInterceptor.java:45)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:161)
	... 9 more
Caused by: java.lang.RuntimeException: Inizializzazione di GovPay fallita: java.lang.Exception: Il path indicato nella property "it.govpay.batch.estrattoConto.pathEsportazione" (/var/govpay/estrattoConto) non esiste o non e' un folder.
	at it.govpay.ejb.StartupEjb.init(StartupEjb.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_80]
	at org.jboss.as.ee.component.ManagedReferenceLifecycleMethodInterceptorFactory$ManagedReferenceLifecycleMethodInterceptor.processInvocation(ManagedReferenceLifecycleMethodInterceptorFactory.java:130)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.weld.injection.WeldInjectionInterceptor.processInvocation(WeldInjectionInterceptor.java:73)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ee.component.ManagedReferenceInterceptorFactory$ManagedReferenceInterceptor.processInvocation(ManagedReferenceInterceptorFactory.java:95)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:228)
	... 18 more
Caused by: java.lang.Exception: Il path indicato nella property "it.govpay.batch.estrattoConto.pathEsportazione" (/var/govpay/estrattoConto) non esiste o non e' un folder.
	at it.govpay.core.utils.GovpayConfig.readProperties(GovpayConfig.java:272)
	at it.govpay.ejb.StartupEjb.init(StartupEjb.java:93)
	... 35 more
Caused by: java.lang.Exception: Il path indicato nella property "it.govpay.batch.estrattoConto.pathEsportazione" (/var/govpay/estrattoConto) non esiste e non puo' essere creato.
	at it.govpay.core.utils.GovpayConfig.readProperties(GovpayConfig.java:270)
	... 36 more

10:55:45,187 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-8) Class Path entry jaxb-api.jar in "/C:/Users/xxxx/jboss-as-7.1.1.Final/bin/content/govpayConsole.war/WEB-INF/lib/jaxb-impl-2.1.13.jar"  does not point to a valid jar for a Class-Path reference.
10:55:45,263 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-8) Class Path entry activation.jar in "/C:/Users/xxxx/jboss-as-7.1.1.Final/bin/content/govpayConsole.war/WEB-INF/lib/jaxb-impl-2.1.13.jar"  does not point to a valid jar for a Class-Path reference.
10:55:45,263 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-8) Class Path entry jsr173_1.0_api.jar in "/C:/Users/xxxx/jboss-as-7.1.1.Final/bin/content/govpayConsole.war/WEB-INF/lib/jaxb-impl-2.1.13.jar"  does not point to a valid jar for a Class-Path reference.
10:55:45,284 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-8) Class Path entry jaxb1-impl.jar in "/C:/Users/xxxx/jboss-as-7.1.1.Final/bin/content/govpayConsole.war/WEB-INF/lib/jaxb-impl-2.1.13.jar"  does not point to a valid jar for a Class-Path reference.
10:55:45,301 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-8) Class Path entry xml-apis.jar in "/C:/Users/xxxx/jboss-as-7.1.1.Final/bin/content/govpayConsole.war/WEB-INF/lib/serializer-2.7.1.jar"  does not point to a valid jar for a Class-Path reference.
10:55:45,312 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-8) Class Path entry xercesImpl.jar in "/C:/Users/xxxx/jboss-as-7.1.1.Final/bin/content/govpayConsole.war/WEB-INF/lib/xalan-2.7.1.jar"  does not point to a valid jar for a Class-Path reference.
10:55:45,323 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-8) Class Path entry xml-apis.jar in "/C:/Users/xxxx/jboss-as-7.1.1.Final/bin/content/govpayConsole.war/WEB-INF/lib/xalan-2.7.1.jar"  does not point to a valid jar for a Class-Path reference.
10:55:45,334 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-8) Class Path entry serializer.jar in "/C:/Users/xxxx/jboss-as-7.1.1.Final/bin/content/govpayConsole.war/WEB-INF/lib/xalan-2.7.1.jar"  does not point to a valid jar for a Class-Path reference.
10:55:45,726 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/govpayConsole]] (MSC service thread 1-1) Exception sending context initialized event to listener instance of class it.govpay.web.InitListener: java.lang.RuntimeException: Inizializzazione di GovPay Console fallita: org.openspcoop2.utils.UtilsException: Lookup jndiResource [java:/govpay] failed: Error looking up govpay, service service jboss.naming.context.java.govpay is not started
	at it.govpay.web.InitListener.contextInitialized(InitListener.java:64) [classes:]
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3392) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3850) [jbossweb-7.0.13.Final.jar:]
	at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:90) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]
Caused by: org.openspcoop2.utils.UtilsException: Lookup jndiResource [java:/govpay] failed: Error looking up govpay, service service jboss.naming.context.java.govpay is not started
	at org.openspcoop2.utils.datasource.DataSourceFactory.newInstance(DataSourceFactory.java:120) [openspcoop2_utils-2.3.8.jar:]
	at it.govpay.bd.ConnectionManager.initialize(ConnectionManager.java:64) [govpay-orm-2.3.3.0.jar:]
	at it.govpay.web.InitListener.contextInitialized(InitListener.java:62) [classes:]
	... 8 more
Caused by: javax.naming.NameNotFoundException: Error looking up govpay, service service jboss.naming.context.java.govpay is not started
	at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:126)
	at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:74)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:178)
	at org.jboss.as.naming.InitialContext.lookup(InitialContext.java:113)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:214)
	at javax.naming.InitialContext.lookup(InitialContext.java:411) [rt.jar:1.7.0_80]
	at org.openspcoop2.utils.resources.GestoreJNDI.lookup(GestoreJNDI.java:78) [openspcoop2_utils-2.3.8.jar:]
	at org.openspcoop2.utils.datasource.DataSourceFactory.newInstance(DataSourceFactory.java:118) [openspcoop2_utils-2.3.8.jar:]
	... 10 more

10:55:45,875 ERROR [org.apache.catalina.core.StandardContext] (MSC service thread 1-1) Error listenerStart
10:55:45,878 ERROR [org.apache.catalina.core.StandardContext] (MSC service thread 1-1) Context [/govpayConsole] startup failed due to previous errors
10:55:45,895 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC00001: Failed to start service jboss.web.deployment.default-host./govpayConsole: org.jboss.msc.service.StartException in service jboss.web.deployment.default-host./govpayConsole: JBAS018040: Failed to start context
	at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:95)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]

10:55:45,933 INFO  [org.jboss.as] (MSC service thread 1-7) JBAS015951: Admin console listening on http://127.0.0.1:9990
10:55:45,937 ERROR [org.jboss.as] (MSC service thread 1-7) JBAS015875: JBoss AS 7.1.1.Final "Brontes" started (with errors) in 12545ms - Started 401 of 650 services (8 services failed or missing dependencies, 240 services are passive or on-demand)

10:55:46,797 ERROR [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) {"JBAS014653: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-2" => {"JBAS014771: Services with missing/unavailable dependencies" => ["jboss.data-source.govpayjboss.jdbc-driver.mysql-connector-java-5_1_42-bin_jarMissing[jboss.data-source.govpayjboss.jdbc-driver.mysql-connector-java-5_1_42-bin_jar]"]}}}
10:55:46,825 ERROR [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) JBAS014654: Composite operation was rolled back
10:55:46,833 ERROR [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) JBAS014654: Composite operation was rolled back
10:55:46,837 ERROR [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) JBAS014654: Composite operation was rolled back
```

Grazie anticipatamente per il supporto

**Comment by nardil** [comment]
Ciao @pievealessandro,
dall'errore che mi hai riportato, vedo la seguente segnalazione:

> Caused by: java.lang.Exception: Il path indicato nella property "it.govpay.batch.estrattoConto.pathEsportazione" (/var/govpay/estrattoConto) non esiste o non e' un folder.
	at it.govpay.core.utils.GovpayConfig.readProperties(GovpayConfig.java:272)
	at it.govpay.ejb.StartupEjb.init(StartupEjb.java:93)
	... 35 more

Dovresti quindi verificare che il folder `/var/govpay/estrattoConto` esista e che l'utente con cui e' in esecuzione JBoss abbia i diritti di lettura e scrittura su di esso.

Ciao,
Lorenzo

**Comment by pievealessandro** [comment]
Ciao, ti ringrazio per la disponibilità e la velocità con cui hai risposto.
Ho creato la folder richiesta, ma fallisce comunque.

12:05:54,131 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-4) MSC00001: Failed to start service jboss.deployment.subunit."govpay.ear"."govpay-web-2.3.3.0.war".component.StartupEjb.START: org.jboss.msc.service.StartException in service jboss.deployment.subunit."govpay.ear"."govpay-web-2.3.3.0.war".component.StartupEjb.START: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1767) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]
Caused by: java.lang.IllegalStateException: JBAS011048: Failed to construct component instance
	at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:163)
	at org.jboss.as.ee.component.BasicComponent.createInstance(BasicComponent.java:85)
	at org.jboss.as.ejb3.component.singleton.SingletonComponent.getComponentInstance(SingletonComponent.java:116)
	at org.jboss.as.ejb3.component.singleton.SingletonComponent.start(SingletonComponent.java:130)
	at org.jboss.as.ee.component.ComponentStartService.start(ComponentStartService.java:44)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746) [jboss-msc-1.0.2.GA.jar:1.0.2.GA]
	... 3 more
Caused by: javax.ejb.EJBException: java.lang.RuntimeException: Inizializzazione GovPay 2.3.3.0 (build d09b8f4) fallita.
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.handleExceptionInOurTx(CMTTxInterceptor.java:166)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:230)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.requiresNew(CMTTxInterceptor.java:333)
	at org.jboss.as.ejb3.tx.SingletonLifecycleCMTTxInterceptor.processInvocation(SingletonLifecycleCMTTxInterceptor.java:56)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ee.component.TCCLInterceptor.processInvocation(TCCLInterceptor.java:45)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61)
	at org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:161)
	... 9 more
Caused by: java.lang.RuntimeException: Inizializzazione GovPay 2.3.3.0 (build d09b8f4) fallita.
	at it.govpay.ejb.StartupEjb.init(StartupEjb.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) [rt.jar:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) [rt.jar:1.7.0_80]
	at org.jboss.as.ee.component.ManagedReferenceLifecycleMethodInterceptorFactory$ManagedReferenceLifecycleMethodInterceptor.processInvocation(ManagedReferenceLifecycleMethodInterceptorFactory.java:130)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.weld.injection.WeldInjectionInterceptor.processInvocation(WeldInjectionInterceptor.java:73)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ee.component.ManagedReferenceInterceptorFactory$ManagedReferenceInterceptor.processInvocation(ManagedReferenceInterceptorFactory.java:95)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:288)
	at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:228)
	... 18 more
Caused by: org.openspcoop2.utils.UtilsException: Lookup jndiResource [java:/govpay] failed: Error looking up govpay, service service jboss.naming.context.java.govpay is not started
	at org.openspcoop2.utils.datasource.DataSourceFactory.newInstance(DataSourceFactory.java:120)
	at it.govpay.bd.ConnectionManager.initialize(ConnectionManager.java:64)
	at it.govpay.ejb.StartupEjb.init(StartupEjb.java:158)
	... 35 more
Caused by: javax.naming.NameNotFoundException: Error looking up govpay, service service jboss.naming.context.java.govpay is not started
	at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:126)
	at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:74)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:178)
	at org.jboss.as.naming.InitialContext.lookup(InitialContext.java:113)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:214)
	at javax.naming.InitialContext.lookup(InitialContext.java:411) [rt.jar:1.7.0_80]
	at org.openspcoop2.utils.resources.GestoreJNDI.lookup(GestoreJNDI.java:78)
	at org.openspcoop2.utils.datasource.DataSourceFactory.newInstance(DataSourceFactory.java:118)
	... 37 more

12:05:54,334 ERROR [org.apache.catalina.core.ContainerBase.[jboss.web].[default-host].[/govpayConsole]] (MSC service thread 1-8) Exception sending context initialized event to listener instance of class it.govpay.web.InitListener: java.lang.RuntimeException: Inizializzazione di GovPay Console fallita: org.openspcoop2.utils.UtilsException: Lookup jndiResource [java:/govpay] failed: Error looking up govpay, service service jboss.naming.context.java.govpay is not started
	at it.govpay.web.InitListener.contextInitialized(InitListener.java:64) [classes:]
	at org.apache.catalina.core.StandardContext.contextListenerStart(StandardContext.java:3392) [jbossweb-7.0.13.Final.jar:]
	at org.apache.catalina.core.StandardContext.start(StandardContext.java:3850) [jbossweb-7.0.13.Final.jar:]
	at org.jboss.as.web.deployment.WebDeploymentService.start(WebDeploymentService.java:90) [jboss-as-web-7.1.1.Final.jar:7.1.1.Final]
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1811)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1746)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [rt.jar:1.7.0_80]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [rt.jar:1.7.0_80]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.7.0_80]
Caused by: org.openspcoop2.utils.UtilsException: Lookup jndiResource [java:/govpay] failed: Error looking up govpay, service service jboss.naming.context.java.govpay is not started
	at org.openspcoop2.utils.datasource.DataSourceFactory.newInstance(DataSourceFactory.java:120) [openspcoop2_utils-2.3.8.jar:]
	at it.govpay.bd.ConnectionManager.initialize(ConnectionManager.java:64) [govpay-orm-2.3.3.0.jar:]
	at it.govpay.web.InitListener.contextInitialized(InitListener.java:62) [classes:]
	... 8 more
Caused by: javax.naming.NameNotFoundException: Error looking up govpay, service service jboss.naming.context.java.govpay is not started
	at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:126)
	at org.jboss.as.naming.ServiceBasedNamingStore.lookup(ServiceBasedNamingStore.java:74)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:178)
	at org.jboss.as.naming.InitialContext.lookup(InitialContext.java:113)
	at org.jboss.as.naming.NamingContext.lookup(NamingContext.java:214)
	at javax.naming.InitialContext.lookup(InitialContext.java:411) [rt.jar:1.7.0_80]
	at org.openspcoop2.utils.resources.GestoreJNDI.lookup(GestoreJNDI.java:78) [openspcoop2_utils-2.3.8.jar:]
	at org.openspcoop2.utils.datasource.DataSourceFactory.newInstance(DataSourceFactory.java:118) [openspcoop2_utils-2.3.8.jar:]
	... 10 more

12:05:54,599 ERROR [org.apache.catalina.core.StandardContext] (MSC service thread 1-8) Error listenerStart


[server.txt](https://github.com/link-it/GovPay/files/1124302/server.txt)

**Comment by nardil** [comment]
@pievealessandro 

Nel log di deploy si individua questo errore che indica il la mancata lookup del datasource:

> Caused by: org.openspcoop2.utils.UtilsException: Lookup jndiResource [java:/govpay] failed: Error looking up govpay, service service jboss.naming.context.java.govpay is not started

Controllando il server.txt che hai allegato si risale a questo errore:

> 12:05:55,384 ERROR [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) {"JBAS014653: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-2" => {"JBAS014771: Services with missing/unavailable dependencies" => ["jboss.data-source.govpayjboss.jdbc-driver.mysql-connector-java-5_1_42-bin_jarMissing[jboss.data-source.govpayjboss.jdbc-driver.mysql-connector-java-5_1_42-bin_jar]"]}}}

L'errore quindi sembra riferire il la mancata disponibilita' del driver jdbc indicato nella configurazione del datasource. Dovresti quindi verificare il corretto deploy del datasource.

Lorenzo

**Comment by pievealessandro** [comment]
Ti ringrazio ancora per la disponibilità, ho risolto passando da mysql a postgres.
