### ISSUE TITLE
ancora configurazione wildfly per gestione SSL

### ISSUE THREAD

**Issue by mallomix** [link-it/govpay#412]
Sono quasi alla disperazione.
alzando i log a debug di wildfly, ai tentativi di connettermi al server in modalità https sia per l'accesso alla dashboard che nell'invocazione dei servizi RT, prendo questo errore:

__2021-10-04 14:53:22,578 DEBUG [io.undertow.request.io] (default I/O-6) UT005013: An IOException occurred: javax.net.ssl.SSLHandshakeException: UT000140: Initial SSL/TLS data is not a handshake record
	at io.undertow.protocols.ssl.ALPNHackClientHelloExplorer.exploreClientHello(ALPNHackClientHelloExplorer.java:84)
	at io.undertow.protocols.ssl.ALPNHackSSLEngine.unwrap(ALPNHackSSLEngine.java:205)
	at io.undertow.server.protocol.http.ALPNLimitingSSLEngine.unwrap(ALPNLimitingSSLEngine.java:159)
	at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:738)
	at io.undertow.protocols.ssl.SslConduit.read(SslConduit.java:567)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
	at io.undertow.server.protocol.http.AlpnOpenListener$AlpnConnectionListener.handleEvent(AlpnOpenListener.java:350)
	at io.undertow.server.protocol.http.AlpnOpenListener.handleEvent(AlpnOpenListener.java:307)
	at io.undertow.server.protocol.http.AlpnOpenListener.handleEvent(AlpnOpenListener.java:67)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$DelegatingChannelListener.handleEvent(ChannelListeners.java:1092)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:132)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)_

_2021-10-04 14:53:24,970 DEBUG [io.undertow.request] (default I/O-7) UT005013: An IOException occurred: javax.net.ssl.SSLHandshakeException: UT000140: Initial SSL/TLS data is not a handshake record
	at io.undertow.protocols.ssl.ALPNHackClientHelloExplorer.exploreClientHello(ALPNHackClientHelloExplorer.java:84)
	at io.undertow.protocols.ssl.ALPNHackSSLEngine.unwrap(ALPNHackSSLEngine.java:205)
	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
	at io.undertow.server.protocol.http.ALPNLimitingSSLEngine.unwrap(ALPNLimitingSSLEngine.java:91)
	at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:757)
	at io.undertow.protocols.ssl.SslConduit.doHandshake(SslConduit.java:648)
	at io.undertow.protocols.ssl.SslConduit.access$900(SslConduit.java:63)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1137)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)_

_2021-10-04 14:53:25,788 DEBUG [io.undertow.request] (management I/O-2) Matched prefix path /management for path /management
2021-10-04 14:53:25,788 DEBUG [io.undertow.request.security] (management I/O-2) Setting authentication required for exchange HttpServerExchange{ POST /management}
2021-10-04 14:53:25,788 DEBUG [io.undertow.request.security] (management task-2) Authenticated as admin, roles []
2021-10-04 14:53:25,788 DEBUG [org.jboss.as.domain.management] (External Management Request Threads -- 1) Identification of operation not progressing after [15000000000] ns has been requested
2021-10-04 14:53:26,158 DEBUG [io.undertow.request.io] (default I/O-4) UT005014: Failed to parse request: io.undertow.util.BadRequestException: UT000165: Invalid character 
 in request-target
	at io.undertow.server.protocol.http.HttpRequestParser.handlePath(HttpRequestParser.java:382)
	at io.undertow.server.protocol.http.HttpRequestParser.handle(HttpRequestParser.java:248)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:187)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:132)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)__

**disabilitando nello standalone.xml l'http2 sia per http che per https, arrivo a govpay dicendomi che la connessione non è protetta con la possibilità di fare un'eccezione con un fantomatico certificato "localhost" che non so cosa sia. In questo modo riesco ad accedere alla dashboard ma all'inserimento delle credenziali ottengo questo errore sui server.log di wildfly:**

__2021-10-04 16:40:12,594 DEBUG [io.undertow.request.io] (default I/O-2) Error reading request: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.EngineInputRecord.bytesInCompletePacket(EngineInputRecord.java:156)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:868)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:738)
	at io.undertow.protocols.ssl.SslConduit.read(SslConduit.java:567)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:158)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$DelegatingChannelListener.handleEvent(ChannelListeners.java:1092)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:132)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)_

_2021-10-04 16:40:14,851 DEBUG [io.undertow.request] (management I/O-1) Matched prefix path /management for path /management
2021-10-04 16:40:14,851 DEBUG [io.undertow.request.security] (management I/O-1) Setting authentication required for exchange HttpServerExchange{ POST /management}
2021-10-04 16:40:14,851 DEBUG [io.undertow.request.security] (management task-1) Authenticated as admin, roles []
2021-10-04 16:40:14,851 DEBUG [org.jboss.as.domain.management] (External Management Request Threads -- 1) Identification of operation not progressing after [15000000000] ns has been requested
2021-10-04 16:40:14,967 DEBUG [io.undertow.request.io] (default I/O-2) Error reading request: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.EngineInputRecord.bytesInCompletePacket(EngineInputRecord.java:156)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:868)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:738)
	at io.undertow.protocols.ssl.SslConduit.read(SslConduit.java:567)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:158)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$DelegatingChannelListener.handleEvent(ChannelListeners.java:1092)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:132)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)_

_2021-10-04 16:40:16,108 DEBUG [io.undertow.request.io] (default I/O-4) UT005014: Failed to parse request: io.undertow.util.BadRequestException: UT000165: Invalid character 
 in request-target
	at io.undertow.server.protocol.http.HttpRequestParser.handlePath(HttpRequestParser.java:382)
	at io.undertow.server.protocol.http.HttpRequestParser.handle(HttpRequestParser.java:248)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:187)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:132)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)__

posso in qualche modo avere un recap della configurazione dello standalone.xml e dei trustore e keystore? Io li referenzio con le java opt, è corretto? per le operazioni da govpay verso Pagopa funziona tutto correttamente

Vi ringrazio del supporto! Ogni suggerimento è oro.

**Comment by mallomix** [comment]
Aggiungo degli aggiornamenti:
->cercando su internet per problemi simili, ho disabilitato il protocollo http2 e referenziato il keystore che contiene il certificato per govpaytest.iss.it nello standalone.xml.

dopo questa modifica ha ripreso tutto a funzionare e accedendo a govpaytest.iss.it mi da il giusto certificato e mi mette in sicurezza la connessione.

adesso però provando a scaricare il WSDL delle ricevute telematiche ottengo a console questo errore:

_2021-10-05 09:14:15,513 DEBUG [io.undertow.request] (default I/O-2) Matched prefix path /govpay/frontend/api/pagopa for path /govpay/frontend/api/pagopa/PagamentiTelematiciRTservice
2021-10-05 09:14:15,513 DEBUG [io.undertow.request.security] (default task-2) Attempting to authenticate /govpay/frontend/api/pagopa/PagamentiTelematiciRTservice, authentication required: false
2021-10-05 09:14:15,513 DEBUG [io.undertow.request.security] (default task-2) Authentication outcome was NOT_ATTEMPTED with method io.undertow.security.impl.CachedAuthenticatedSessionMechanism@7318906c for /govpay/frontend/api/pagopa/PagamentiTelematiciRTservice
2021-10-05 09:14:15,513 DEBUG [io.undertow.request.security] (default task-2) Authentication result was ATTEMPTED for /govpay/frontend/api/pagopa/PagamentiTelematiciRTservice
2021-10-05 09:14:15,559 DEBUG [io.undertow.request] (management I/O-1) Matched prefix path /management for path /management
2021-10-05 09:14:15,559 DEBUG [io.undertow.request.security] (management I/O-1) Setting authentication required for exchange HttpServerExchange{ POST /management}
2021-10-05 09:14:15,559 DEBUG [io.undertow.request.security] (management task-1) Authenticated as admin, roles []
2021-10-05 09:14:15,559 DEBUG [org.jboss.as.domain.management] (External Management Request Threads -- 1) Identification of operation not progressing after [15000000000] ns has been requested
2021-10-05 09:14:15,575 DEBUG [io.undertow.request] (default I/O-2) Matched default handler path /favicon.ico
2021-10-05 09:14:15,798 DEBUG [io.undertow.request.io] (default I/O-6) UT005014: Failed to parse request: io.undertow.util.BadRequestException: UT000165: Invalid character 
 in request-target
	at io.undertow.server.protocol.http.HttpRequestParser.handlePath(HttpRequestParser.java:382)
	at io.undertow.server.protocol.http.HttpRequestParser.handle(HttpRequestParser.java:248)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:187)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:132)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)_

_2021-10-05 09:14:17,534 DEBUG [io.undertow.request.io] (default I/O-5) Error reading request: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.EngineInputRecord.bytesInCompletePacket(EngineInputRecord.java:156)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:868)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:738)
	at io.undertow.protocols.ssl.SslConduit.read(SslConduit.java:567)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:158)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$DelegatingChannelListener.handleEvent(ChannelListeners.java:1092)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:132)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)_

_2021-10-05 09:14:19,982 DEBUG [io.undertow.request.io] (default I/O-1) Error reading request: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.EngineInputRecord.bytesInCompletePacket(EngineInputRecord.java:156)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:868)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:738)
	at io.undertow.protocols.ssl.SslConduit.read(SslConduit.java:567)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:158)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$DelegatingChannelListener.handleEvent(ChannelListeners.java:1092)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:132)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)_

_2021-10-05 09:14:20,774 DEBUG [io.undertow.request.io] (default I/O-6) UT005014: Failed to parse request: io.undertow.util.BadRequestException: UT000165: Invalid character 
 in request-target
	at io.undertow.server.protocol.http.HttpRequestParser.handlePath(HttpRequestParser.java:382)
	at io.undertow.server.protocol.http.HttpRequestParser.handle(HttpRequestParser.java:248)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:187)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:132)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)_

_2021-10-05 09:14:22,564 DEBUG [io.undertow.request.io] (default I/O-6) Error reading request: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at sun.security.ssl.EngineInputRecord.bytesInCompletePacket(EngineInputRecord.java:156)
	at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:868)
	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:781)
	at io.undertow.protocols.ssl.SslConduit.doUnwrap(SslConduit.java:738)
	at io.undertow.protocols.ssl.SslConduit.read(SslConduit.java:567)
	at org.xnio.conduits.ConduitStreamSourceChannel.read(ConduitStreamSourceChannel.java:127)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:158)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.ChannelListeners$DelegatingChannelListener.handleEvent(ChannelListeners.java:1092)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:132)
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479)_

credo siamo quasi vicini alla soluzione. Grazie del supporto.

**Comment by mallomix** [comment]
Ancora aggiornamenti a beneficio di tutti e per avere conferma che la strada che sto percorrendo ha un senso:

impostando su standalone.xml i listener http e https come segue, sono riuscito a utilizzare connettività https terminata sull'AS wildfly con autenticazione SSL per i servizi pagopa RT:

_<security-realm name="ApplicationRealm">
                <server-identities>
                    <ssl>
                     <keystore path="keystore.jks" relative-to="jboss.server.config.dir" keystore-password="secret" alias="govpaytest.iss.it (GEANT OV RSA CA 4)" key-password="secret"/>
                    </ssl>
                </server-identities>
                <authentication>
                    <local default-user="$local" allowed-users="*" skip-group-loading="true"/>
                    <properties path="application-users.properties" relative-to="jboss.server.config.dir"/>
                </authentication>
                <authorization>
                    <properties path="application-roles.properties" relative-to="jboss.server.config.dir"/>
                </authorization>
            </security-realm>_

_<subsystem xmlns="urn:jboss:domain:undertow:10.0" default-server="default-server" default-virtual-host="default-host" default-servlet-container="default" default-security-domain="other" statistics-enabled="${wildfly.undertow.statistics-enabled:${wildfly.statistics-enabled:false}}">
            <buffer-cache name="default"/>
            <server name="default-server">
                <http-listener name="default" socket-binding="http" redirect-socket="https" enable-http2="false" allow-unescaped-characters-in-url="true" url-charset="windows-1250" />
                <https-listener name="https" socket-binding="https" security-realm="ApplicationRealm" enable-http2="false" allow-unescaped-characters-in-url="true" url-charset="windows-1250" enabled-protocols="SSLv3, TLSv1.2" verify-client="REQUESTED"/>
                <host name="default-host" alias="localhost">
                    <location name="/" handler="welcome-content"/>
                    <http-invoker security-realm="ApplicationRealm"/>
                </host>
            </server>
            <servlet-container name="default">
                <jsp-config/>
                <websockets/>
            </servlet-container>
            <handlers>
                <file name="welcome-content" path="${jboss.home.dir}/welcome-content"/>
            </handlers>
        </subsystem>_

in particolare la necessità di referenziare il keystore nell'ApplicationRealm e non basta usare le JAVAOPT per referenziare keystore e trusttore,  e la necessità di dire al listener http di usare gli escape in URL e la codifica 1250. Inoltre su quello HTTPS abilitare SSLv3, TLSv1.2 e verify-client = REQUESTED.

Adesso mi rimane da capire perchè da MOZILLA tutto funziona mentre da CHROME e EDGE mi dice che la connessione non è sicura e non accedo ai servizi RT per 401. 
Quindi non ho la certezza che tutto sta funzionado. Con Mozilla il check globale è ok, con gli altri browser invece NO. Cosa serve fare ? ho provato anche a importare il certificato govpaytest.iss.it ma nulla. Anche Postman non riesce a scaricare il WSDL anche importando il certificato chiave pubblica o quello con la chiave privata indistintamente.

Ho bisogno di capire quale deve essere la configurazione ufficiale affinchè GOVPAY funzioni correttamente. Non ho trovato nessuna specifica dettagliata per configurare wildfly in una configurazione di default funzionante.
Io ho un'architettura semplice in cui L'application server ora riceve tutto il traffico https senza intermediari, non ci sono reverse proxy. 

Vi ringrazio per il supporto

**Comment by ind87moving** [comment]
Ciao @mallomix,
nel [commento del 05/10/2021 ](https://github.com/link-it/govpay/issues/412#issuecomment-934207347)non si visualizzano le configuraioni che avevi riportato.
Riusciresti gentilmente ad integrarle?
Grazie

**Comment by mallomix** [comment]
Buongiorno, mi scuso per l'attesa e ovviamente inserisco le informazioni che alla fine mi hanno permesso di integrare con successo govpay dal punto di vista delle API protette da SSL:

•	C:\”_home wildfly_”\standalone\configuration\Standalone.xml

// Certificato con cui il server si presenta preso dal keystore.jks che va copiato nella directory:
// C:\”home wildfly”\standalone\configuration\

<security-realm name="ApplicationRealm">
 <server-identities>
  <ssl>
   <keystore path="keystore.jks" 
             relative-to="jboss.server.config.dir" 
             keystore-password="_pwd_" 
             alias="_nomeAliasCertificato_" 
             key-password="_pwd_"
   />												
  </ssl>
 </server-identities>


// configurazione del protocollo HTTPS
<server name="default-server">
 <http-listener name="default" 
                socket-binding="http" 
                redirect-socket="https" 
                enable-http2="false" // questo per la sicurezza ed evitare Client-side desync (CSD) vulnerability, deve essere messo a TRUE
                allow-unescaped-characters-in-url="true" 
                url-charset="windows-1250" />
 <https-listener name="https" 
                 socket-binding="https" 
                 security-realm="ApplicationRealm" 
                 enable-http2="false" 
                 allow-unescaped-characters-in-url="true" 
                 url-charset="windows-1250" 
                 enabled-protocols="SSLv3, TLSv1.2. TLSv1.1, SSLv2" 
                 verify-client="REQUESTED"/>
 <host name="default-host" alias="localhost">
 <location name="/" handler="welcome-content"/>
 <http-invoker security-realm="ApplicationRealm"/>
 </host>
</server>

Se avete davanti al server wildfly che espone i servizi GOVPAY, un bilanciatore, proxy, firewall, waf, insomma qualsiasi cosa che possa manipolare il tunner HTTPS, impostare su tale apparato il pass-through dell'handshake SSL al server di destinazione (wildfly) oppure se necessario che il WAF o quello che sia, termini l'handshake SSL, allora deve fare rencrypting con lo stesso certificato non alterando la provenienza dell'http request. 
Il server govpay deve verificare che sia pagopa a chiamare i servizi govpay.

**Comment by nardil** [comment]
> Se avete davanti al server wildfly che espone i servizi GOVPAY, un bilanciatore, proxy, firewall, waf, insomma qualsiasi cosa che possa manipolare il tunner HTTPS, impostare su tale apparato il pass-through dell'handshake SSL al server di destinazione (wildfly) oppure se necessario che il WAF o quello che sia, termini l'handshake SSL, allora deve fare rencrypting con lo stesso certificato non alterando la provenienza dell'http request. Il server govpay deve verificare che sia pagopa a chiamare i servizi govpay.

Nel caso citato da @mallomix  non e' possibile fare `rencrypting con lo stesso certificato non alterando la provenienza` della richiesta  (non si ha la chiave privata di pagoPA per farlo). 

Si puo' gestire la presenza di un componente di rete che intermedia il colloquio tra pagoPA e GovPay in molteplici modi:
- Non termina la sessione SSL ed opera in modalita' pass-through
- Termina la sessione SSL ed inoltra la richiesta su protocollo AJP
- Termina la sessione SSL ed esegue il forward del certificato client come header http `X-Client-Cert`

La configurazione [Spring Security delle API pagoPA](https://govpay.readthedocs.io/it/latest/integrazione/api/autenticazione/index.html#integrazione-autenticazione) di GovPay devono essere coerenti con la modalita' scelta:
- SSL nei primi due casi (configurazione di default)
- SSL-HEADER nel terzo caso
