### ISSUE TITLE
Errore durante il deploy dell'ear

### ISSUE THREAD

**Issue by hal-berto** [link-it/govpay#426]
Buongiorno,
ho eseguito l'installer e seguito le istruzioni di dispiegamento (Wildfly 25, database MySql).
Quando tento di avviare Wildfly, in console viene visualizzato questo errore:

11:28:21,234 ERROR [boot] (ServerService Thread Pool -- 83) Errore durante predisposizione del contesto: org.openspcoop2.utils.UtilsException
11:28:21,236 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 83) MSC000001: Failed to start service jboss.deployment.subunit."govpay.ear"."api-user-3.4.3-SNAPSHOT.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.subunit."govpay.ear"."api-user-3.4.3-SNAPSHOT.war".undertow-deployment: java.lang.RuntimeException: java.lang.RuntimeException: Inizializzazione di GovPay-API-User 3.4.3-SNAPSHOT (build ${git.c) fallita.
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:90)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Inizializzazione di GovPay-API-User 3.4.3-SNAPSHOT (build ${git.c) fallita.
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:257)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:105)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:87)
        ... 8 more
Caused by: java.lang.RuntimeException: Inizializzazione di GovPay-API-User 3.4.3-SNAPSHOT (build ${git.c) fallita.
        at it.govpay.core.utils.StartupUtils.startup(StartupUtils.java:178)
        at it.govpay.user.listener.InitListener.contextInitialized(InitListener.java:48)
        at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
        at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:219)
        at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:187)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
        at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1544)
        at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:255)
        ... 10 more
Caused by: org.openspcoop2.utils.UtilsException
        at org.openspcoop2.utils.logger.LoggerFactory._newLogger(LoggerFactory.java:122)
        at org.openspcoop2.utils.logger.LoggerFactory.newLogger(LoggerFactory.java:104)
        at it.govpay.core.utils.service.context.GpContextFactory.newBatchContext(GpContextFactory.java:38)
        at it.govpay.core.utils.StartupUtils.startup(StartupUtils.java:159)
        ... 21 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openspcoop2.utils.logger.LoggerFactory._newLogger(LoggerFactory.java:113)
        ... 24 more
Caused by: java.lang.ClassCastException: org.jboss.logmanager.log4j.JBossLoggerContext cannot be cast to org.apache.logging.log4j.core.LoggerContext
        at org.openspcoop2.utils.LoggerWrapperFactory.getContext(LoggerWrapperFactory.java:110)
        at org.openspcoop2.utils.LoggerWrapperFactory.setLogConfiguration(LoggerWrapperFactory.java:249)
        at org.openspcoop2.utils.logger.config.Log4jConfig._setConfigurationLogger(Log4jConfig.java:134)
        at org.openspcoop2.utils.logger.config.Log4jConfig.setConfigurationLogger(Log4jConfig.java:88)
        at org.openspcoop2.utils.logger.log4j.AbstractLog4JLogger.<init>(AbstractLog4JLogger.java:59)
        at org.openspcoop2.utils.logger.log4j.AbstractLog4JLoggerWithContext.<init>(AbstractLog4JLoggerWithContext.java:51)
        at org.openspcoop2.utils.logger.log4j.Log4JLoggerWithBatchContext.<init>(Log4JLoggerWithBatchContext.java:44)
        ... 29 more

Come posso risolvere?
Grazie in anticipo

**Comment by nardil** [comment]
Ciao @hal-berto ,

come indicato nel [manuale di installazione](https://govpay.readthedocs.io/it/latest/installazione/ambiente/index.html), la versione di wildfly supportata e' la 18. Versioni successive possono non essere compatibili con il pacchetto prodotto dall'installer.
