### ISSUE TITLE
Aggiornamento stack applicativo: Java 11, Wildfly 26, Postgres 14

### ISSUE THREAD

**Issue by pintorig** [link-it/govpay#516]
**Necessità:**
Aggiornamento per l'esecuzione nello stack applicativo:
Java 17
Wildfly 26
Postgresql 14

**Comment by pintorig** [comment]
Per eliminare l'errore che si ottiene durante la generazione degli avvisi di pagamento:

```
Error evaluating expression for source text: new java.text.DecimalFormat("#,###,##0.00", new DecimalFormatSymbols(Locale.ITALY)).format(Double.valueOf($F{importo})) + " Euro " +
($F{giorni}.equals(null)?($F{data}.equals(null)?"":" entro il " + $F{data}):" " + $F{tipo} + " " + $F{giorni} + ($F{giorni}.toString().equals("1")?" giorno":" giorni"))
net.sf.jasperreports.engine.JRRuntimeException: net.sf.jasperreports.engine.fill.JRExpressionEvalException: Error evaluating expression for source text: new java.text.DecimalFormat("#,###,##0.00", new DecimalFormatSymbols(Locale.ITALY)).f
ormat(Double.valueOf($F{importo})) + " Euro " +
($F{giorni}.equals(null)?($F{data}.equals(null)?"":" entro il " + $F{data}):" " + $F{tipo} + " " + $F{giorni} + ($F{giorni}.toString().equals("1")?" giorno":" giorni"))
        at net.sf.jasperreports.engine.fill.JRFillSubreport.prepare(JRFillSubreport.java:874) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRFillElementContainer.prepareElements(JRFillElementContainer.java:536) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRFillBand.fill(JRFillBand.java:411) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRFillBand.fill(JRFillBand.java:386) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillColumnBand(JRVerticalFiller.java:2024) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillDetail(JRVerticalFiller.java:748) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReportStart(JRVerticalFiller.java:255) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:115) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:580) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:414) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRFillSubreport.fillSubreport(JRFillSubreport.java:736) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRSubreportRunnable.run(JRSubreportRunnable.java:59) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.AbstractThreadSubreportRunner.run(AbstractThreadSubreportRunner.java:221) ~[jasperreports-6.2.2.jar:6.2.2]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: net.sf.jasperreports.engine.fill.JRExpressionEvalException: Error evaluating expression for source text: new java.text.DecimalFormat("#,###,##0.00", new DecimalFormatSymbols(Locale.ITALY)).format(Double.valueOf($F{importo})) + 
" Euro " +
($F{giorni}.equals(null)?($F{data}.equals(null)?"":" entro il " + $F{data}):" " + $F{tipo} + " " + $F{giorni} + ($F{giorni}.toString().equals("1")?" giorno":" giorni"))
        at net.sf.jasperreports.engine.fill.JREvaluator.evaluate(JREvaluator.java:290) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRCalculator.evaluate(JRCalculator.java:616) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRCalculator.evaluate(JRCalculator.java:584) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRFillElement.evaluateExpression(JRFillElement.java:1164) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRFillTextField.evaluateText(JRFillTextField.java:526) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRFillTextField.evaluate(JRFillTextField.java:510) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRFillElementContainer.evaluate(JRFillElementContainer.java:381) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRFillBand.evaluate(JRFillBand.java:500) ~[jasperreports-6.2.2.jar:6.2.2]
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillColumnBand(JRVerticalFiller.java:2022) ~[jasperreports-6.2.2.jar:6.2.2]
        ... 11 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private char java.text.DecimalFormatSymbols.zeroDigit accessible: module java.base does not "opens java.text" to unnamed module @23faba62
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]

```

basta aggiungere la seguente opzione al momento del lancio della JVM:

```
--add-opens java.base/java.text=ALL-UNNAMED"
```

**Comment by pintorig** [comment]
@marklar79 

L'esecuzione dell'installer con JDK17 fallisce con il seguente errore:

```

BUILD FAILED
/home/zulio/NO_BACKUP/git/govpay/src/main/resources/setup/target/govpay-installer-4.0.0/installer/setup/build.xml:60: Unable to create javax script engine for javascript

Total time: 1 second

```
Da una prima analisi sembra che siano state eliminate delle librerie dalla [JDK15](https://stackoverflow.com/questions/71928637/unable-to-create-javax-script-engine-for-javascript-error-when-trying-to-creat) in poi.
