### ISSUE TITLE
upgrade govpay da 3.4.2 a 3.6.2

### ISSUE THREAD

**Issue by mallomix** [link-it/govpay#560]
## Processo di UPGRADE della piattaforma GOVPAY da una vecchia versiona all'ultima disponibile

Buongiorno,

uso la versione 3.4.2 di govpay e, considerati gli adeguamenti dovuti alle modifiche di PAGOPA, vulnerabilità, fix e funzionalità, ho la necessità di portarlo alla versione più recente.

Ho controllato nella documentazione come fare e trovo dei suggerimenti ma non un piano di migrazione dettagliato con tutti gli step passo passo per migrare la piattaforma. Mi scuso nel caso esistesse e non sono riuscito a trovarlo.

Leggendo però quello che ho trovato forse dovrò fare più step di migrazione (versione per versione) che alla fine oltre al codice dovrebbero consistere nel passare 2 script e 1 copia di un file come di seguito descritto, confermate?:

-     Applicare le patch 3.5.sql e 3.6.sql
-     Copiare il file di configurazione api-jppapdp-applicationContext-security.xml nella directory di lavoro

Nel caso sia così dove trovo gli script ed il file?

Nel caso non sia così che processo dovrei seguire senza perdere i dati di produzione (pendenze, pagamenti) ?

Ringrazio come sempre per la collaborazione,

Cordiali saluti

**Comment by nardil** [comment]
Ciao @mallomix ,

le informazioni per l'aggiornamento sono disponibili [nel manuale online](https://govpay.readthedocs.io/it/latest/installazione/aggiornamento/index.html#aggiornamento-di-versione)

I file necessari sono prodotti dall'installer scaricabile dalla sezione [releases](https://github.com/link-it/govpay/releases).

**Comment by mallomix** [comment]
> Ciao @mallomix ,
> 
> le informazioni per l'aggiornamento sono disponibili [nel manuale online](https://govpay.readthedocs.io/it/latest/installazione/aggiornamento/index.html#aggiornamento-di-versione)
> 
> I file necessari sono prodotti dall'installer scaricabile dalla sezione [releases](https://github.com/link-it/govpay/releases).

Ciao Nardil,

esattamente come dicevo, da manuale online non ci sono gli step necessari ma solo dei suggerimenti. Mi confermi quindi che io vado sul server dove è installata la versione 3.4.2, uso l'installer della 3.6.2 e tutto funziona automaticamente senza perdere nessun dato?

Ti ringrazio del supporto ma avendo un sistema in PRODUZIONE che paga tramite govpay devo essere sicuro di quello che faccio per evitare problemi gravi

Un saluto e grazie ancora

**Comment by nardil** [comment]
Non vogliono essere suggerimenti, ma step operativi di aggiornamento. L'installer si occupa solo di produrre gli artefatti necessari all'installazione o all'aggiornamento (le patch SQL, i file di configurazione Spring Security, l'EAR), l'aggiornamento effettivo deve essere gestito manualmente come indicato nel manuale:

1. Applicare le patch al database in base alla versione di provenienza
2. Aggiungere i file di configurazione Spring Security mancanti (se configurata l'esternalizzazione del file)
3. Sostituire l'ear

Ovviamente si devono seguire le buone pratiche del caso: testare la procedura prima in ambiente di collaudo, eseguire il backup del db e del sistema per un eventuale rollback, etc...

**Comment by mallomix** [comment]
Ciao Nardil,

allora sto provando a migrare un govpay 3.3.3 funzionante in 3.4.2, come primo step propedeutico a fare la migrazione alla 3.6.2 (oppure 3.6.5 appena uscita).

Seguendo le istruzioni scrupolosamente, il risultato in fase di deploy dell'EAR da parte di wildfly è il seguente errore che non riusciamo a capire:

Premessa: 
- script 3.4.sql eseguito con successo.
- test connettività wildfly verso postgres OK.

```
2023-01-18 16:24:23,983 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-7) WFLYSRV0027: Starting deployment of "govpay.ear" (runtime-name: "govpay.ear")
2023-01-18 16:24:32,085 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0059: Class Path entry xml-apis.jar in /C:/wildflyDir/bin/content/govpay.ear/lib/serializer-2.7.1.jar  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,085 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0059: Class Path entry xercesImpl.jar in /C:/wildflyDir/bin/content/govpay.ear/lib/xalan-2.7.1.jar  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,085 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0059: Class Path entry xml-apis.jar in /C:/wildflyDir/bin/content/govpay.ear/lib/xalan-2.7.1.jar  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,085 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0059: Class Path entry serializer.jar in /C:/wildflyDir/bin/content/govpay.ear/lib/xalan-2.7.1.jar  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,163 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0207: Starting subdeployment (runtime-name: "api-pagopa-3.4.2.war")
2023-01-18 16:24:32,163 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-2) WFLYSRV0207: Starting subdeployment (runtime-name: "web-console-3.4.2.war")
2023-01-18 16:24:32,163 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-7) WFLYSRV0207: Starting subdeployment (runtime-name: "web-connector-3.4.2.war")
2023-01-18 16:24:32,163 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0207: Starting subdeployment (runtime-name: "api-ragioneria-3.4.2.war")
2023-01-18 16:24:32,163 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0207: Starting subdeployment (runtime-name: "api-backoffice-3.4.2.war")
2023-01-18 16:24:32,163 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0207: Starting subdeployment (runtime-name: "api-pagamento-3.4.2.war")
2023-01-18 16:24:32,163 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0207: Starting subdeployment (runtime-name: "api-pendenze-3.4.2.war")
2023-01-18 16:24:32,163 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0207: Starting subdeployment (runtime-name: "api-user-3.4.2.war")
2023-01-18 16:24:32,210 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0059: Class Path entry lib/jaxb-api-2.3.0.jar in /C:/wildflyDir/bin/content/govpay.ear/api-user-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,304 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0059: Class Path entry lib/swagger-parser-1.0.41.jar in /C:/wildflyDir/bin/content/govpay.ear/api-user-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,304 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0059: Class Path entry lib/jackson-dataformat-yaml-2.9.8.jar in /C:/wildflyDir/bin/content/govpay.ear/api-user-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,304 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0059: Class Path entry lib/snakeyaml-1.23.jar in /C:/wildflyDir/bin/content/govpay.ear/api-user-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,304 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0059: Class Path entry lib/jackson-dataformat-xml-2.9.8.jar in /C:/wildflyDir/bin/content/govpay.ear/api-user-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,304 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0059: Class Path entry lib/stax2-api-3.1.4.jar in /C:/wildflyDir/bin/content/govpay.ear/api-user-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,304 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0059: Class Path entry lib/jackson-coreutils-1.8.jar in /C:/wildflyDir/bin/content/govpay.ear/api-user-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,304 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-6) WFLYSRV0059: Class Path entry lib/jsr305-2.0.1.jar in /C:/wildflyDir/bin/content/govpay.ear/api-user-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,335 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-4) WFLYSRV0059: Class Path entry lib/jaxb-api-2.3.0.jar in /C:/wildflyDir/bin/content/govpay.ear/web-connector-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,351 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0059: Class Path entry lib/jaxb-api-2.3.0.jar in /C:/wildflyDir/bin/content/govpay.ear/api-ragioneria-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,382 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0059: Class Path entry lib/jaxb-api-2.3.0.jar in /C:/wildflyDir/bin/content/govpay.ear/api-pendenze-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,398 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0059: Class Path entry lib/jaxb-api-2.3.0.jar in /C:/wildflyDir/bin/content/govpay.ear/api-pagamento-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,398 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0059: Class Path entry lib/swagger-parser-1.0.41.jar in /C:/wildflyDir/bin/content/govpay.ear/api-pagamento-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,398 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0059: Class Path entry lib/jackson-dataformat-yaml-2.9.8.jar in /C:/wildflyDir/bin/content/govpay.ear/api-pagamento-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,398 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0059: Class Path entry lib/snakeyaml-1.23.jar in /C:/wildflyDir/bin/content/govpay.ear/api-pagamento-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,398 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0059: Class Path entry lib/jackson-dataformat-xml-2.9.8.jar in /C:/wildflyDir/bin/content/govpay.ear/api-pagamento-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,398 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0059: Class Path entry lib/stax2-api-3.1.4.jar in /C:/wildflyDir/bin/content/govpay.ear/api-pagamento-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,398 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0059: Class Path entry lib/jackson-coreutils-1.8.jar in /C:/wildflyDir/bin/content/govpay.ear/api-pagamento-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,398 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-3) WFLYSRV0059: Class Path entry lib/jsr305-2.0.1.jar in /C:/wildflyDir/bin/content/govpay.ear/api-pagamento-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:32,429 WARN  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0059: Class Path entry lib/jaxb-api-2.3.0.jar in /C:/wildflyDir/bin/content/govpay.ear/api-backoffice-3.4.2.war  does not point to a valid jar for a Class-Path reference.
2023-01-18 16:24:33,398 INFO  [org.jboss.weld.deployer] (MSC service thread 1-4) WFLYWELD0003: Processing weld deployment govpay.ear
2023-01-18 16:24:33,538 INFO  [org.jboss.weld.deployer] (MSC service thread 1-1) WFLYWELD0003: Processing weld deployment web-console-3.4.2.war
2023-01-18 16:24:33,538 INFO  [org.jboss.weld.deployer] (MSC service thread 1-8) WFLYWELD0003: Processing weld deployment api-pendenze-3.4.2.war
2023-01-18 16:24:33,538 INFO  [org.jboss.weld.deployer] (MSC service thread 1-7) WFLYWELD0003: Processing weld deployment api-user-3.4.2.war
2023-01-18 16:24:33,538 INFO  [org.jboss.weld.deployer] (MSC service thread 1-6) WFLYWELD0003: Processing weld deployment api-ragioneria-3.4.2.war
2023-01-18 16:24:33,538 INFO  [org.jboss.weld.deployer] (MSC service thread 1-5) WFLYWELD0003: Processing weld deployment web-connector-3.4.2.war
2023-01-18 16:24:33,538 INFO  [org.jboss.weld.deployer] (MSC service thread 1-4) WFLYWELD0003: Processing weld deployment api-pagamento-3.4.2.war
2023-01-18 16:24:33,554 INFO  [org.jboss.weld.deployer] (MSC service thread 1-2) WFLYWELD0003: Processing weld deployment api-pagopa-3.4.2.war
2023-01-18 16:24:33,554 INFO  [org.jboss.weld.deployer] (MSC service thread 1-3) WFLYWELD0003: Processing weld deployment api-backoffice-3.4.2.war
2023-01-18 16:24:34,864 INFO  [org.infinispan.configuration.cache.MemoryConfigurationBuilder] (MSC service thread 1-2) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
2023-01-18 16:24:34,864 INFO  [org.infinispan.configuration.cache.MemoryConfigurationBuilder] (MSC service thread 1-2) ISPN000152: Passivation configured without an eviction policy being selected. Only manually evicted entities will be passivated.
2023-01-18 16:24:34,880 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 89) WFLYCLINF0002: Started default-server cache from web container
2023-01-18 16:24:34,989 INFO  [org.jboss.as.clustering.infinispan] (ServerService Thread Pool -- 90) WFLYCLINF0002: Started govpay.ear cache from web container
2023-01-18 16:24:35,177 INFO  [io.smallrye.metrics] (MSC service thread 1-8) MicroProfile: Metrics activated
2023-01-18 16:24:35,786 INFO  [io.undertow.servlet] (ServerService Thread Pool -- 90) No Spring WebApplicationInitializer types detected on classpath
2023-01-18 16:24:36,469 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 90) MSC000001: Failed to start service jboss.deployment.subunit."govpay.ear"."api-user-3.4.2.war".undertow-deployment: org.jboss.msc.service.StartException in service jboss.deployment.subunit."govpay.ear"."api-user-3.4.2.war".undertow-deployment: java.lang.RuntimeException: java.lang.RuntimeException: Inizializzazione di GovPay-API-User 3.4.2 (build b69b983) fallita.
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:81)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1982)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.lang.Thread.run(Unknown Source)
	at org.jboss.threads.JBossThread.run(JBossThread.java:485)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Inizializzazione di GovPay-API-User 3.4.2 (build b69b983) fallita.
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:254)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:96)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:78)
	... 8 more
Caused by: java.lang.RuntimeException: Inizializzazione di GovPay-API-User 3.4.2 (build b69b983) fallita.
	at it.govpay.core.utils.StartupUtils.startupServices(StartupUtils.java:197)
	at it.govpay.user.listener.InitListener.contextInitialized(InitListener.java:52)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:217)
	at io.undertow.servlet.core.DeploymentManagerImpl$1.call(DeploymentManagerImpl.java:186)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1504)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:252)
	... 10 more
Caused by: org.openspcoop2.utils.UtilsException: Riscontrato errore durante l'inizializzazione della risorsa JMX [domini]: it.govpay.cache.anagrafica.user:type=domini
	at org.openspcoop2.utils.cache.CacheJMXUtils.register(CacheJMXUtils.java:72)
	at org.openspcoop2.utils.cache.CacheJMXUtils.register(CacheJMXUtils.java:54)
	at it.govpay.bd.anagrafica.AnagraficaManager.<init>(AnagraficaManager.java:151)
	at it.govpay.bd.anagrafica.AnagraficaManager.newInstance(AnagraficaManager.java:167)
	at it.govpay.core.utils.StartupUtils.startupServices(StartupUtils.java:192)
	... 22 more
Caused by: org.openspcoop2.utils.jmx.RisorseJMXException: Riscontrato errore durante l'inizializzazione della risorsa JMX [domini]: it.govpay.cache.anagrafica.user:type=domini
	at org.openspcoop2.utils.jmx.GestoreRisorseJMX.registerMBean(GestoreRisorseJMX.java:256)
	at org.openspcoop2.utils.jmx.GestoreRisorseJMX.registerMBean(GestoreRisorseJMX.java:239)
	at org.openspcoop2.utils.cache.CacheJMXUtils.register(CacheJMXUtils.java:70)
	... 26 more
Caused by: javax.management.InstanceAlreadyExistsException: it.govpay.cache.anagrafica.user:type=domini
	at com.sun.jmx.mbeanserver.Repository.addMBean(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerWithRepository(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerDynamicMBean(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerObject(Unknown Source)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(Unknown Source)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(Unknown Source)
	at org.jboss.as.jmx.PluggableMBeanServerImpl$TcclMBeanServer.registerMBean(PluggableMBeanServerImpl.java:1499)
	at org.jboss.as.jmx.PluggableMBeanServerImpl.registerMBean(PluggableMBeanServerImpl.java:871)
	at org.openspcoop2.utils.jmx.GestoreRisorseJMX.registerMBean(GestoreRisorseJMX.java:248)
	... 28 more

2023-01-18 16:24:36,469 ERROR [org.jboss.as.controller.management-operation] (DeploymentScanner-threads - 1) WFLYCTL0013: Operation ("full-replace-deployment") failed - address: ([]) - failure description: {
    "WFLYCTL0080: Failed services" => {"jboss.deployment.subunit.\"govpay.ear\".\"api-user-3.4.2.war\".undertow-deployment" => "java.lang.RuntimeException: java.lang.RuntimeException: Inizializzazione di GovPay-API-User 3.4.2 (build b69b983) fallita.
    Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Inizializzazione di GovPay-API-User 3.4.2 (build b69b983) fallita.
    Caused by: java.lang.RuntimeException: Inizializzazione di GovPay-API-User 3.4.2 (build b69b983) fallita.
    Caused by: org.openspcoop2.utils.UtilsException: Riscontrato errore durante l'inizializzazione della risorsa JMX [domini]: it.govpay.cache.anagrafica.user:type=domini
    Caused by: org.openspcoop2.utils.jmx.RisorseJMXException: Riscontrato errore durante l'inizializzazione della risorsa JMX [domini]: it.govpay.cache.anagrafica.user:type=domini
    Caused by: javax.management.InstanceAlreadyExistsException: it.govpay.cache.anagrafica.user:type=domini"},
    "WFLYCTL0412: Required services that are not installed:" => [
        "jboss.deployment.subunit.\"govpay.ear\".\"web-connector-3.4.2.war\".deploymentCompleteService",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-backoffice-3.4.2.war\".beanmanager",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-pagamento-3.4.2.war\".deploymentCompleteService",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-pagopa-3.4.2.war\".beanmanager",
        "jboss.deployment.subunit.\"govpay.ear\".\"web-connector-3.4.2.war\".beanmanager",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-backoffice-3.4.2.war\".deploymentCompleteService",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-pendenze-3.4.2.war\".deploymentCompleteService",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-pendenze-3.4.2.war\".beanmanager",
        "jboss.deployment.subunit.\"govpay.ear\".\"web-console-3.4.2.war\".deploymentCompleteService",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-pagamento-3.4.2.war\".beanmanager",
        "jboss.deployment.subunit.\"govpay.ear\".\"web-console-3.4.2.war\".beanmanager",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-ragioneria-3.4.2.war\".beanmanager",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-pagopa-3.4.2.war\".deploymentCompleteService",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-ragioneria-3.4.2.war\".deploymentCompleteService"
    ],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => [
        "jboss.deployment.subunit.\"govpay.ear\".\"api-pagamento-3.4.2.war\".INSTALL is missing [jboss.deployment.subunit.\"govpay.ear\".\"api-pagopa-3.4.2.war\".deploymentCompleteService]",
        "jboss.deployment.subunit.\"govpay.ear\".\"web-console-3.4.2.war\".batch.artifact.factory is missing [jboss.deployment.subunit.\"govpay.ear\".\"web-console-3.4.2.war\".beanmanager]",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-pendenze-3.4.2.war\".INSTALL is missing [jboss.deployment.subunit.\"govpay.ear\".\"web-connector-3.4.2.war\".deploymentCompleteService]",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-pagamento-3.4.2.war\".batch.artifact.factory is missing [jboss.deployment.subunit.\"govpay.ear\".\"api-pagamento-3.4.2.war\".beanmanager]",
        "jboss.deployment.subunit.\"govpay.ear\".\"web-connector-3.4.2.war\".batch.artifact.factory is missing [jboss.deployment.subunit.\"govpay.ear\".\"web-connector-3.4.2.war\".beanmanager]",
        "jboss.deployment.subunit.\"govpay.ear\".\"web-console-3.4.2.war\".INSTALL is missing [jboss.deployment.subunit.\"govpay.ear\".\"api-backoffice-3.4.2.war\".deploymentCompleteService]",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-ragioneria-3.4.2.war\".INSTALL is missing [jboss.deployment.subunit.\"govpay.ear\".\"api-pendenze-3.4.2.war\".deploymentCompleteService]",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-backoffice-3.4.2.war\".batch.artifact.factory is missing [jboss.deployment.subunit.\"govpay.ear\".\"api-backoffice-3.4.2.war\".beanmanager]",
        "jboss.deployment.subunit.\"govpay.ear\".\"web-connector-3.4.2.war\".INSTALL is missing [jboss.deployment.subunit.\"govpay.ear\".\"api-pagamento-3.4.2.war\".deploymentCompleteService]",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-pagopa-3.4.2.war\".batch.artifact.factory is missing [jboss.deployment.subunit.\"govpay.ear\".\"api-pagopa-3.4.2.war\".beanmanager]",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-backoffice-3.4.2.war\".INSTALL is missing [jboss.deployment.subunit.\"govpay.ear\".\"api-ragioneria-3.4.2.war\".deploymentCompleteService]",
        "jboss.deployment.unit.\"govpay.ear\".deploymentCompleteService is missing [jboss.deployment.subunit.\"govpay.ear\".\"api-pendenze-3.4.2.war\".deploymentCompleteService, jboss.deployment.subunit.\"govpay.ear\".\"web-console-3.4.2.war\".deploymentCompleteService, jboss.deployment.subunit.\"govpay.ear\".\"api-backoffice-3.4.2.war\".deploymentCompleteService, jboss.deployment.subunit.\"govpay.ear\".\"api-ragioneria-3.4.2.war\".deploymentCompleteService, jboss.deployment.subunit.\"govpay.ear\".\"web-connector-3.4.2.war\".deploymentCompleteService, jboss.deployment.subunit.\"govpay.ear\".\"api-pagamento-3.4.2.war\".deploymentCompleteService, jboss.deployment.subunit.\"govpay.ear\".\"api-pagopa-3.4.2.war\".deploymentCompleteService]",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-ragioneria-3.4.2.war\".batch.artifact.factory is missing [jboss.deployment.subunit.\"govpay.ear\".\"api-ragioneria-3.4.2.war\".beanmanager]",
        "jboss.deployment.subunit.\"govpay.ear\".\"api-pendenze-3.4.2.war\".batch.artifact.factory is missing [jboss.deployment.subunit.\"govpay.ear\".\"api-pendenze-3.4.2.war\".beanmanager]"
    ]
}
2023-01-18 16:24:36,703 INFO  [org.jboss.as.server] (DeploymentScanner-threads - 1) WFLYSRV0016: Replaced deployment "govpay.ear" with deployment "govpay.ear"
2023-01-18 16:24:36,703 INFO  [org.jboss.as.controller] (DeploymentScanner-threads - 1) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.deployment.subunit."govpay.ear"."api-user-3.4.2.war".undertow-deployment: java.lang.RuntimeException: java.lang.RuntimeException: Inizializzazione di GovPay-API-User 3.4.2 (build b69b983) fallita.
```

Ti ringrazio del supporto

Saluti

**Comment by mallomix** [comment]
Ciao Nardil,

in effetti riavviando il server stamattina ha funzionato, senza toccare nulla! Ieri avevo riavviato riavviato ma nulla! comunque tutto ok.

TI spiego il discorso della migrazione per versioni intermedie.  Avendo degli ambienti di test interni con versioni diverse, volevo riportare tutti gli ambienti alla versione di PRODUZIONE che attualmente è la 3.4.2 e poi testare la migrazione alla 3.6.5 su questi ambienti per poi replicarla in PRODUZIONE senza sorprese.

Ti ringrazio. Lascio aperto il topic nel caso riscontrassi difficoltà nell'upgrade finale
