### ISSUE TITLE
Errore undertow: UT005014: Failed to parse request: java.lang.RuntimeException: UT000037: Failed to parse path in HTTP request  - quando ricevo la ricevuta da PAGOPA

### ISSUE THREAD

**Issue by mallomix** [link-it/govpay#599]
**Ambiente PAGOPA UAT - test nuova connettività -**

1) govpay installato 3.6.6
2) chiamate verso https://api.uat.platform.pagopa.it/nodo-auth/nodo-per-pa/v1  **FUNZIONANTI**
3) ricezione RT su endpoint GOVPAY https://domainName/govpay/frontend/api/pagopa/PagamentiTelematiciRTservice   **KO** (errore in oggetto su log wildfly)
4) principal usato in configurazione intermediario in govpay: `CN=forwarder.uat.platform.pagopa.it`
5) nel trustore inseriti il certificato forwarder.uat.platform.pagopa.it e anche tutta la root chain

6) la configurazione standalone.xml relativamente alla sezione http-listener e https-listener è la seguente:
```
<http-listener name="default" socket-binding="http" url-charset="windows-1252" allow-unescaped-characters-in-url="true" redirect-socket="https" enable-http2="true"/>
<https-listener name="https" socket-binding="https" url-charset="windows-1252" allow-unescaped-characters-in-url="true" security-realm="ApplicationRealm" verify-client="REQUESTED" enabled-protocols="SSLv3, TLSv1.2, TLSv1.1, TLSv1, SSLv2" enable-http2="true"/>
```

Di seguito lo stacktrace relativo all'errore che rilevo lato wildfly quando arriva la ricenuta da PAGOPA nuova connettività:

```
2023-08-01 14:56:55,304 DEBUG [io.undertow.request.io] (default I/O-5) UT005014: Failed to parse request: java.lang.RuntimeException: UT000037: Failed to parse path in HTTP request
	at io.undertow.server.protocol.http.HttpRequestParser.handlePath(HttpRequestParser.java:408)
	at io.undertow.server.protocol.http.HttpRequestParser.handle(HttpRequestParser.java:248)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:187)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.AlpnOpenListener$AlpnConnectionListener.handleEvent(AlpnOpenListener.java:388)
	at io.undertow.server.protocol.http.AlpnOpenListener$AlpnConnectionListener.handleEvent(AlpnOpenListener.java:335)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1176)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)

2023-08-01 14:56:55,308 TRACE [org.xnio.safe-close] (default I/O-5) Closing resource io.undertow.protocols.ssl.UndertowSslConnection@35abcf07
2023-08-01 14:56:55,309 TRACE [io.undertow.request.io] (default I/O-5) Exception closing read side of SSL channel: javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
	at sun.security.ssl.Alerts.getSSLException(Unknown Source)
	at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source)
	at sun.security.ssl.SSLEngineImpl.fatal(Unknown Source)
	at sun.security.ssl.SSLEngineImpl.closeInbound(Unknown Source)
	at io.undertow.protocols.ssl.ALPNHackSSLEngine.closeInbound(ALPNHackSSLEngine.java:279)
	at io.undertow.server.protocol.http.ALPNLimitingSSLEngine.closeInbound(ALPNLimitingSSLEngine.java:169)
	at io.undertow.protocols.ssl.SslConduit.notifyReadClosed(SslConduit.java:612)
	at io.undertow.protocols.ssl.SslConduit.closed(SslConduit.java:1020)
	at io.undertow.protocols.ssl.SslConduit.close(SslConduit.java:1118)
	at io.undertow.protocols.ssl.UndertowSslConnection.closeAction(UndertowSslConnection.java:149)
	at org.xnio.Connection.close(Connection.java:132)
	at org.xnio.IoUtils.safeClose(IoUtils.java:152)
	at io.undertow.server.protocol.http.HttpReadListener$1.writeDone(HttpReadListener.java:291)
	at io.undertow.util.StringWriteChannelListener.setup(StringWriteChannelListener.java:62)
	at io.undertow.server.protocol.http.HttpReadListener.sendBadRequestAndClose(HttpReadListener.java:298)
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:257)
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162)
	at io.undertow.server.protocol.http.AlpnOpenListener$AlpnConnectionListener.handleEvent(AlpnOpenListener.java:388)
	at io.undertow.server.protocol.http.AlpnOpenListener$AlpnConnectionListener.handleEvent(AlpnOpenListener.java:335)
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
	at org.xnio.conduits.ReadReadyHandler$ChannelListenerHandler.readReady(ReadReadyHandler.java:66)
	at io.undertow.protocols.ssl.SslConduit$SslReadReadyHandler.readReady(SslConduit.java:1176)
	at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:89)
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)

```

con la vecchia connettività tutto funziona correttamente. Sembrerebbe che a wildfly non piace come arriva la richiesta http ma non ci sono dettagli aggiuntivi. **Pagopa non mi ha saputo aiutare.** 

Grazie come sempre

**Comment by nardil** [comment]
Ciao @mallomix

l'unica differenza che abbiamo riscontrato nel passaggio da GAD è che pagoPA richiede il server esponga tutta la chain del certificato. Questo perchè pagoPA esegue il trust delle intermediate CA, pertanto se non esposto fallisce l'handshake.

Spero che questa informazione possa aiutarti a individuare il problema. Non abbiamo installazioni con terminazione SSL su WildFly di cui condividere la configurazione.

**Comment by mallomix** [comment]
Ovviamente tutta la chain è trustata.  Ma non credevo di essere l'unico a usare l'SSL mutua verifica, anche perchè è PAGOPA che lo richiede. Come fanno gli altri? magari cambio modalità volentieri

**Comment by nardil** [comment]
> Ovviamente tutta la chain è trustata.

La chain non deve essere in trust, ma esposta verso il client di pagoPA. Puoi verificarlo ad esempio con [OpenSSL](https://www.openssl.org/docs/man1.0.2/man1/openssl-s_client.html) con l'opzione `showcerts` per verificare che tutta la chain sia presentata al client

Per quanto riguarda le installazioni che gestiamo, ovviamente e' attiva la mutua autenticazione, ma la terminazione della connessione SSL in erogazione viene terminata da un componente a monte (load balancer, reverse proxy, ...).
