### ISSUE TITLE
Errore NullPointer in gestione log risposta con faultBean

### ISSUE THREAD

**Issue by SbGibson** [link-it/GovPay#60]
In alcuni casi di risposta con errore dal nodo dei pagamenti in GovPay 2.5.4 otteniamo un errore di nullPointerException. 
Per capire se fosse un problema nostro abbiamo analizzato il codice e sembrerebbe che l'errore sia nel file it/govpay/core/business/model/Risposta.java nel metodo toString.
In tutto il metodo si fa riferimento a this.faultBean ma a volte il metodo viene richiamato dal metodo log passandogli un faultBean recuperato dalla faultMap e this.faultBean è nullo.
Il controllo sul null viene fatto sul parametro che poi però non viene utilizzato per recuperare le info. 

Se la nostra analisi è sbagliata possiamo fornirvi una risposta di esempio che restituire questo errore.

**Comment by SbGibson** [comment]
Questa è l'envelope di risposta ricevuta dal nodo

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header/><soap:Body><ns4:nodoInviaCarrelloRPTRisposta xmlns:ns4="http://ws.pagamenti.telematici.gov/" xmlns:ns3="http://ws.pagamenti.telematici.gov/ppthead"><esitoComplessivoOperazione>KO</esitoComplessivoOperazione><listaErroriRPT><fault><faultCode>PPT_SEMANTICA</faultCode><faultString>Errore semantico</faultString><id>NodoDeiPagamentiSPC</id><description>Errore in Carrello [ed82d255f49f4619bbb70f33bfe3d152] -  RPT [idDominio=01234567890/IUV=001800000002271/CCP=012345678901234567]: I valori di IBAN indicati nei versamenti (IT11I1111111111111111111111) non fanno parte degli IBAN validi per la PA</description><serial>1</serial></fault><fault><faultCode>PPT_SEMANTICA</faultCode><faultString>Errore semantico</faultString><id>NodoDeiPagamentiSPC</id><description>Errore in Carrello [ed82d255f49f4619bbb70f33bfe3d152] -  RPT [idDominio=0123456789/IUV=001800000002372/CCP=012345678901234567]: I valori di IBAN indicati nei versamenti (IT11I1111111111111111111111) non fanno parte degli IBAN validi per la PA</description><serial>2</serial></fault></listaErroriRPT></ns4:nodoInviaCarrelloRPTRisposta></soap:Body></soap:Envelope> 
 
questa l'envelope di risposta di govpay

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"/><soap:Body><ns2:gpAvviaTransazionePagamentoResponse xmlns:ns2="http://www.govpay.it/servizi/v2_3/gpPrt/" xmlns:ns3="http://www.govpay.it/servizi/v2_3/gpRnd/" xmlns:ns4="http://www.govpay.it/servizi/commons/" xmlns:ns5="http://www.govpay.it/servizi/v2_3"><codOperazione>db6583f2-c421-4140-b29d-d4cbff6c278e</codOperazione><mittente>GovPay</mittente><codEsito>INTERNAL</codEsito><descrizioneEsito>Errore interno</descrizioneEsito><dettaglioEsito>java.lang.NullPointerException</dettaglioEsito></ns2:gpAvviaTransazionePagamentoResponse></soap:Body></soap:Envelope>

**Comment by SbGibson** [comment]
Lo stack dell'errore

ERROR | it.govpay.core.exceptions.GovPayException:115 | c2a7d5ce-caab-470e-bc3e-78b59281d6bf | [INTERNAL] java.lang.NullPointerException
it.govpay.core.exceptions.GovPayException: java.lang.NullPointerException
	at it.govpay.web.ws.v2_3.PagamentiTelematiciGPPrtImpl.gpAvviaTransazionePagamento(PagamentiTelematiciGPPrtImpl.java:368) [govpay-ejb-2.5.4.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.jboss.as.ee.component.ManagedReferenceMethodInterceptor.processInvocation(ManagedReferenceMethodInterceptor.java:52) [wildfly-ee-8.2.1.Final.jar!/:8.2.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63) [wildfly-ee-8.2.1.Final.jar!/:8.2.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.invocation.WeavedInterceptor.processInvocation(WeavedInterceptor.java:53) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.as.ee.component.interceptors.UserInterceptorFactory$1.processInvocation(UserInterceptorFactory.java:63) [wildfly-ee-8.2.1.Final.jar!/:8.2.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45) [wildfly-ee-8.2.1.Final.jar!/:8.2.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.invocation.InitialInterceptor.processInvocation(InitialInterceptor.java:21) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.as.ee.component.interceptors.ComponentDispatcherInterceptor.processInvocation(ComponentDispatcherInterceptor.java:53) [wildfly-ee-8.2.1.Final.jar!/:8.2.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.as.webservices.deployers.WSComponentInstanceAssociationInterceptor.processInvocation(WSComponentInstanceAssociationInterceptor.java:49) [wildfly-webservices-server-integration-8.2.1.Final.jar!/:8.2.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:326) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:448) [wildfly-security-manager-1.0.0.Final.jar!/:1.0.0.Final]
	at org.jboss.invocation.AccessCheckingInterceptor.processInvocation(AccessCheckingInterceptor.java:61) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.invocation.InterceptorContext.run(InterceptorContext.java:326) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.invocation.PrivilegedWithCombinerInterceptor.processInvocation(PrivilegedWithCombinerInterceptor.java:80) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:309) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:61) [jboss-invocation-1.2.1.Final.jar!/:1.2.1.Final]
	at org.jboss.as.ee.component.ViewService$View.invoke(ViewService.java:185) [wildfly-ee-8.2.1.Final.jar!/:8.2.1.Final]
	at org.jboss.as.webservices.invocation.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:130) [wildfly-webservices-server-integration-8.2.1.Final.jar!/:8.2.1.Final]
	at org.jboss.wsf.stack.cxf.JBossWSInvoker.performInvocation(JBossWSInvoker.java:175) [jbossws-cxf-server-4.3.2.Final.jar!/:4.3.2.Final]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:104) [cxf-api-2.7.13.jar!/:2.7.13]
	at org.apache.cxf.jaxws.AbstractJAXWSMethodInvoker.invoke(AbstractJAXWSMethodInvoker.java:237) [cxf-rt-frontend-jaxws-2.7.13.jar!/:2.7.13]
	at org.apache.cxf.jaxws.JAXWSMethodInvoker.invoke(JAXWSMethodInvoker.java:69) [cxf-rt-frontend-jaxws-2.7.13.jar!/:2.7.13]
	at org.jboss.wsf.stack.cxf.JBossWSInvoker.invoke(JBossWSInvoker.java:146) [jbossws-cxf-server-4.3.2.Final.jar!/:4.3.2.Final]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:58) [cxf-api-2.7.13.jar!/:2.7.13]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_51]
	at org.apache.cxf.workqueue.SynchronousExecutor.execute(SynchronousExecutor.java:37) [cxf-api-2.7.13.jar!/:2.7.13]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:107) [cxf-api-2.7.13.jar!/:2.7.13]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:272) [cxf-api-2.7.13.jar!/:2.7.13]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121) [cxf-api-2.7.13.jar!/:2.7.13]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:241) [cxf-rt-transports-http-2.7.13.jar!/:2.7.13]
	at org.jboss.wsf.stack.cxf.RequestHandlerImpl.handleHttpRequest(RequestHandlerImpl.java:97) [jbossws-cxf-server-4.3.2.Final.jar!/:4.3.2.Final]
	at org.jboss.wsf.stack.cxf.transport.ServletHelper.callRequestHandler(ServletHelper.java:131) [jbossws-cxf-server-4.3.2.Final.jar!/:4.3.2.Final]
	at org.jboss.wsf.stack.cxf.CXFServletExt.invoke(CXFServletExt.java:88) [jbossws-cxf-server-4.3.2.Final.jar!/:4.3.2.Final]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:286) [cxf-rt-transports-http-2.7.13.jar!/:2.7.13]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:206) [cxf-rt-transports-http-2.7.13.jar!/:2.7.13]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) [jboss-servlet-api_3.1_spec-1.0.0.Final.jar!/:1.0.0.Final]
	at org.jboss.wsf.stack.cxf.CXFServletExt.service(CXFServletExt.java:136) [jbossws-cxf-server-4.3.2.Final.jar!/:4.3.2.Final]
	at org.jboss.wsf.spi.deployment.WSFServlet.service(WSFServlet.java:140) [jbossws-spi-2.3.1.Final.jar!/:2.3.1.Final]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [jboss-servlet-api_3.1_spec-1.0.0.Final.jar!/:1.0.0.Final]
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86) [undertow-servlet-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62) [undertow-servlet-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36) [undertow-servlet-1.1.8.Final.jar!/:1.1.8.Final]
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78) [wildfly-undertow-8.2.1.Final.jar!/:8.2.1.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131) [undertow-servlet-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57) [undertow-servlet-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.server.handlers.DisableCacheHandler.handleRequest(DisableCacheHandler.java:33) [undertow-core-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.security.handlers.AuthenticationConstraintHandler.handleRequest(AuthenticationConstraintHandler.java:51) [undertow-core-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46) [undertow-core-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64) [undertow-servlet-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.servlet.handlers.security.ServletSecurityConstraintHandler.handleRequest(ServletSecurityConstraintHandler.java:56) [undertow-servlet-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58) [undertow-core-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:70) [undertow-servlet-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76) [undertow-core-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.8.Final.jar!/:1.1.8.Final]
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61) [wildfly-undertow-8.2.1.Final.jar!/:8.2.1.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43) [undertow-core-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:261) [undertow-servlet-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:248) [undertow-servlet-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:77) [undertow-servlet-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:167) [undertow-servlet-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199) [undertow-core-1.1.8.Final.jar!/:1.1.8.Final]
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:761) [undertow-core-1.1.8.Final.jar!/:1.1.8.Final]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_51]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_51]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.NullPointerException
	at it.govpay.core.business.model.Risposta.toString(Risposta.java:115) ~[govpay-core-2.5.4.jar:?]
	at it.govpay.core.business.model.Risposta.getLog(Risposta.java:107) ~[govpay-core-2.5.4.jar:?]
	at it.govpay.core.business.Pagamento.avviaTransazione(Pagamento.java:413) ~[govpay-core-2.5.4.jar:?]
	at it.govpay.core.business.Pagamento.avviaTransazione(Pagamento.java:171) ~[govpay-core-2.5.4.jar:?]
	at it.govpay.web.ws.v2_3.PagamentiTelematiciGPPrtImpl.gpAvviaTransazionePagamento(PagamentiTelematiciGPPrtImpl.java:338) ~[govpay-ejb-2.5.4.jar:?]
	... 82 more
