### ISSUE TITLE
Errore compilazione codice

### ISSUE THREAD

**Issue by pperliti** [link-it/govpay#619]
Ciao.
Ho letto tutta la documentazione di GovPay ma ho qualche dubbio a cui spero possiate rispondere.

Ho provato a clonare il progetto GovPay (branch `master`), importandolo in Eclipse, ma l'IDE mi segnala diversi errori di compilazione.
Ad esempio, ho diverse classi non risolte per i package `it.govpay.core.utils.appio.model` e `it.govpay.core.utils.appio.impl`

Non mi è dunque chiaro se i sorgenti sono utilizzabili _as-is_ o se ci sono parti non rilasciate/disponibili pubblicamente.
Grazie del chiarimento.

![image](https://github.com/link-it/govpay/assets/1265443/0507e9c4-2fe8-45b5-b5e8-b75bf671cd95)

**Comment by pperliti** [comment]
Inoltre provando a eseguire `mvn -Denv=installer_template -e clean install` ottengo il seguente errore:

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  02:05 min
> [INFO] Finished at: 2023-09-19T12:27:59+02:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.3.1:resources (default-resources) on project stampe: filtering C:\MyWorkspace\govpay\jars\stampe\src\main\resources\avviso\postale\AvvisoPagamento.jasper to C:\MyWorkspace\govpay\jars\stampe\target\classes\avviso\postale\AvvisoPagamento.jasper failed with MalformedInputException: Input length = 1 -> [Help 1]
> org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:3.3.1:resources (default-resources) on project stampe: filtering C:\MyWorkspace\govpay\jars\stampe\src\main\resources\avviso\postale\AvvisoPagamento.jasper to C:\MyWorkspace\govpay\jars\stampe\target\classes\avviso\postale\AvvisoPagamento.jasper failed with MalformedInputException

**Comment by pperliti** [comment]
Lanciando Maven generate-sources invece ottengo l'errore:

> [INFO] [1m-----------------------< [0;36mit.govpay:appio-beans[0;1m >------------------------[m
> [INFO] [1mBuilding GovPay - jars - AppIO beans 3.7.4                        [7/25][m
> [INFO]   from jars\appio-beans\pom.xml
> [INFO] [1m--------------------------------[ jar ]---------------------------------[m
> [INFO] 
> [INFO] [1m--- [0;32mclean:3.2.0:clean[m [1m(default-clean)[m @ [36mappio-beans[0;1m ---[m
> [INFO] Deleting C:\MyWorkspace\govpay\jars\appio-beans\target
> [INFO] 
> [INFO] [1m--- [0;32mproperties:1.0.0:read-project-properties[m [1m(default)[m @ [36mappio-beans[0;1m ---[m
> [INFO] 
> [INFO] [1m--- [0;32mgit-commit-id:2.2.1:revision[m [1m(get-the-git-infos)[m @ [36mappio-beans[0;1m ---[m
> [INFO] 
> [INFO] [1m--- [0;32mswagger-codegen:3.0.18-gov4j-4:generate[m [1m(generate-sources-appio-client)[m @ [36mappio-beans[0;1m ---[m
> [WARNING] Output directory does not exist, or is inaccessible. No file (.swagger-codegen-ignore) will be evaluated.
> 'processComposedSchemas' codegenModel [CreatedMessageWithContent] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [CreatedMessageWithContent] property 'id'
> 'processComposedSchemas' codegenModel [CreatedMessageWithContent] property 'fiscal_code'
> 'processComposedSchemas' codegenModel [CreatedMessageWithContent] property 'time_to_live'
> 'processComposedSchemas' codegenModel [CreatedMessageWithContent] property 'created_at'
> 'processComposedSchemas' codegenModel [CreatedMessageWithContent] property 'content'
> 'processComposedSchemas' codegenModel [CreatedMessageWithContent] property 'sender_service_id'
> 'processComposedSchemas' codegenModel [DateUTC] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [DateUTC] no properties
> 'processComposedSchemas' codegenModel [EmailAddress] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [EmailAddress] no properties
> 'processComposedSchemas' codegenModel [FiscalCode] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [FiscalCode] no properties
> 'processComposedSchemas' codegenModel [FiscalCodeHash] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [FiscalCodeHash] no properties
> 'processComposedSchemas' codegenModel [GetLimitedProfileByPOSTPayload] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [GetLimitedProfileByPOSTPayload] property 'fiscal_code'
> 'processComposedSchemas' codegenModel [HttpStatusCode] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [HttpStatusCode] no properties
> 'processComposedSchemas' codegenModel [LimitedProfile] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [LimitedProfile] property 'sender_allowed'
> 'processComposedSchemas' codegenModel [LimitedProfile] property 'preferred_languages'
> 'processComposedSchemas' codegenModel [MessageBodyMarkdown] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [MessageBodyMarkdown] no properties
> 'processComposedSchemas' codegenModel [MessageContent] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [MessageContent] property 'subject'
> 'processComposedSchemas' codegenModel [MessageContent] property 'markdown'
> 'processComposedSchemas' codegenModel [MessageContent] property 'payment_data'
> 'processComposedSchemas' codegenModel [MessageContent] property 'prescription_data'
> 'processComposedSchemas' codegenModel [MessageContent] property 'due_date'
> 'processComposedSchemas' codegenModel [MessageCreated] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [MessageCreated] property 'id'
> 'processComposedSchemas' codegenModel [MessageResponseNotificationStatus] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [MessageResponseNotificationStatus] property 'email'
> 'processComposedSchemas' codegenModel [MessageResponseNotificationStatus] property 'webhook'
> 'processComposedSchemas' codegenModel [MessageResponseWithContent] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [MessageResponseWithContent] property 'message'
> 'processComposedSchemas' codegenModel [MessageResponseWithContent] property 'notification'
> 'processComposedSchemas' codegenModel [MessageResponseWithContent] property 'status'
> 'processComposedSchemas' codegenModel [MessageStatusValue] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [MessageStatusValue] no properties
> 'processComposedSchemas' codegenModel [MessageSubject] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [MessageSubject] no properties
> 'processComposedSchemas' codegenModel [NewMessage] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [NewMessage] property 'time_to_live'
> 'processComposedSchemas' codegenModel [NewMessage] property 'content'
> 'processComposedSchemas' codegenModel [NewMessage] property 'default_addresses'
> 'processComposedSchemas' codegenModel [NewMessage] property 'fiscal_code'
> 'processComposedSchemas' codegenModel [NewMessageDefaultAddresses] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [NewMessageDefaultAddresses] property 'email'
> 'processComposedSchemas' codegenModel [NotificationChannelStatusValue] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [NotificationChannelStatusValue] no properties
> 'processComposedSchemas' codegenModel [PaymentAmount] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [PaymentAmount] no properties
> 'processComposedSchemas' codegenModel [PaymentData] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [PaymentData] property 'amount'
> 'processComposedSchemas' codegenModel [PaymentData] property 'notice_number'
> 'processComposedSchemas' codegenModel [PaymentData] property 'invalid_after_due_date'
> 'processComposedSchemas' codegenModel [PaymentNoticeNumber] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [PaymentNoticeNumber] no properties
> 'processComposedSchemas' codegenModel [PreferredLanguage] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [PreferredLanguage] no properties
> 'processComposedSchemas' codegenModel [PreferredLanguages] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [PreferredLanguages] ArraySchema
> 'processComposedSchemas' codegenModel [PrescriberFiscalCode] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [PrescriberFiscalCode] no properties
> 'processComposedSchemas' codegenModel [PrescriptionData] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [PrescriptionData] property 'nre'
> 'processComposedSchemas' codegenModel [PrescriptionData] property 'iup'
> 'processComposedSchemas' codegenModel [PrescriptionData] property 'prescriber_fiscal_code'
> 'processComposedSchemas' codegenModel [PrescriptionIUP] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [PrescriptionIUP] no properties
> 'processComposedSchemas' codegenModel [PrescriptionNRE] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [PrescriptionNRE] no properties
> 'processComposedSchemas' codegenModel [ProblemJson] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [ProblemJson] property 'type'
> 'processComposedSchemas' codegenModel [ProblemJson] property 'title'
> 'processComposedSchemas' codegenModel [ProblemJson] property 'status'
> 'processComposedSchemas' codegenModel [ProblemJson] property 'detail'
> 'processComposedSchemas' codegenModel [ProblemJson] property 'instance'
> 'processComposedSchemas' codegenModel [SubscriptionsFeed] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [SubscriptionsFeed] property 'dateUTC'
> 'processComposedSchemas' codegenModel [SubscriptionsFeed] property 'subscriptions'
> 'processComposedSchemas' codegenModel [SubscriptionsFeed] property 'unsubscriptions'
> 'processComposedSchemas' codegenModel [SubscriptionsList] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [SubscriptionsList] ArraySchema
> 'processComposedSchemas' codegenModel [TimeToLiveSeconds] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [TimeToLiveSeconds] no properties
> 'processComposedSchemas' codegenModel [Timestamp] [io.swagger.codegen.v3.CodegenModel]
> 'processComposedSchemas' codegenModel [Timestamp] no properties
> [ERROR] 
> java.lang.RuntimeException: Could not generate model 'CreatedMessageWithContent'
> 	at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:451)
> 	at io.swagger.codegen.v3.DefaultGenerator.generate(DefaultGenerator.java:779)
> 	at io.swagger.codegen.v3.maven.plugin.CodeGenMojo.execute(CodeGenMojo.java:547)
> 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
> 	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
> 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
> 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
> 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
> 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
> 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
> 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
> 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
> 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
> 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
> 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
> Caused by: com.github.jknack.handlebars.HandlebarsException: /handlebars/Java/licenseInfo.mustache:2:6: java.lang.reflect.InaccessibleObjectException: Unable to make public boolean java.util.Collections$EmptyMap.isEmpty() accessible: module java.base does not "opens java.util" to unnamed module @5b218cf1
>     /handlebars/Java/licenseInfo.mustache:2:6
> 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
> 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
> 	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
> 	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
> 	at com.github.jknack.handlebars.context.MemberValueResolver.cache(MemberValueResolver.java:82)
> 	at com.github.jknack.handlebars.context.MemberValueResolver.resolve(MemberValueResolver.java:54)
> 	at com.github.jknack.handlebars.Context$CompositeValueResolver.resolve(Context.java:199)
> 	at com.github.jknack.handlebars.internal.path.PropertyPath.eval(PropertyPath.java:52)
> 	at com.github.jknack.handlebars.Context$PathExpressionChain.next(Context.java:361)
> 	at com.github.jknack.handlebars.Context$PathExpressionChain.eval(Context.java:381)
> 	at com.github.jknack.handlebars.Context.get(Context.java:621)
> 	at com.github.jknack.handlebars.Context$PartialCtx.get(Context.java:165)
> 	at com.github.jknack.handlebars.internal.Variable.value(Variable.java:183)
> 	at com.github.jknack.handlebars.internal.Variable.merge(Variable.java:160)
> 	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
> 	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
> 	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
> 	at com.github.jknack.handlebars.internal.ForwardingTemplate.apply(ForwardingTemplate.java:86)
> 	at com.github.jknack.handlebars.internal.Partial.merge(Partial.java:228)
> 	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
> 	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
> 	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
> 	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
> 	at com.github.jknack.handlebars.internal.ForwardingTemplate.apply(ForwardingTemplate.java:72)
> 	at io.swagger.codegen.v3.templates.HandlebarTemplateEngine.getRendered(HandlebarTemplateEngine.java:25)
> 	at io.swagger.codegen.v3.DefaultGenerator.processTemplateToFile(DefaultGenerator.java:795)
> 	at io.swagger.codegen.v3.DefaultGenerator.generateModels(DefaultGenerator.java:438)
> 	... 29 more
> Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make public boolean java.util.Collections$EmptyMap.isEmpty() accessible: module java.base does not "opens java.util" to unnamed module @5b218cf1
> 	... 56 more
> [INFO] [1m------------------------------------------------------------------------[m
> [INFO] [1mReactor Summary for GovPay 3.7.4:[m
> [INFO] 
> [INFO] GovPay ............................................. [1;32mSUCCESS[m [ 31.502 s]
> [INFO] GovPay - jars ...................................... [1;32mSUCCESS[m [  8.323 s]
> [INFO] GovPay - jars - TitilliumWeb Fonts ................. [1;32mSUCCESS[m [  5.252 s]
> [INFO] GovPay - jars - XML Adapters ....................... [1;32mSUCCESS[m [  4.183 s]
> [INFO] GovPay - jars - pagoPA beans ....................... [1;32mSUCCESS[m [ 14.926 s]
> [INFO] GovPay - jars - JPPA PdP beans ..................... [1;32mSUCCESS[m [  6.829 s]
> [INFO] GovPay - jars - AppIO beans ........................ [1;31mFAILURE[m [  3.531 s]
> [INFO] GovPay - jars - ORM Beans .......................... [1;33mSKIPPED[m
> [INFO] GovPay - jars - Core beans ......................... [1;33mSKIPPED[m
> [INFO] GovPay - jars - ORM ................................ [1;33mSKIPPED[m
> [INFO] GovPay - jars - Stampe ............................. [1;33mSKIPPED[m
> [INFO] GovPay - jars - Client EC .......................... [1;33mSKIPPED[m
> [INFO] GovPay - jars - Core ............................... [1;33mSKIPPED[m
> [INFO] GovPay - jars - API Commons ........................ [1;33mSKIPPED[m
> [INFO] GovPay - wars ...................................... [1;33mSKIPPED[m
> [INFO] GovPay - wars - REST API User ...................... [1;33mSKIPPED[m
> [INFO] GovPay - wars - REST API Backoffice ................ [1;33mSKIPPED[m
> [INFO] GovPay - wars - REST API Pagamento ................. [1;33mSKIPPED[m
> [INFO] GovPay - wars - REST API Ragioneria ................ [1;33mSKIPPED[m
> [INFO] GovPay - wars - REST API Pendenze .................. [1;33mSKIPPED[m
> [INFO] GovPay - wars - SOAP API pagoPA .................... [1;33mSKIPPED[m
> [INFO] GovPay - wars - SOAP API Maggioli JPPA ............. [1;33mSKIPPED[m
> [INFO] GovPay - wars - Web Controller ..................... [1;33mSKIPPED[m
> [INFO] GovPay - wars - Cruscotto di gestione .............. [1;33mSKIPPED[m
> [INFO] GovPay - ear ....................................... [1;33mSKIPPED[m
> [INFO] [1m------------------------------------------------------------------------[m
> [INFO] [1;31mBUILD FAILURE[m
> [INFO] [1m------------------------------------------------------------------------[m
> [INFO] Total time:  01:14 min
> [INFO] Finished at: 2023-09-19T12:39:54+02:00
> [INFO] [1m------------------------------------------------------------------------[m
> [ERROR] Failed to execute goal [32mio.swagger.codegen.v3:swagger-codegen-maven-plugin:3.0.18-gov4j-4:generate[m [1m(generate-sources-appio-client)[m on project [36mappio-beans[m: [1;31mCode generation failed. See above for the full exception.[m -> [1m[Help 1][m
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
> [ERROR] Re-run Maven using the [1m-X[m switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> [ERROR] 
> [ERROR] After correcting the problems, you can resume the build with the command
> [ERROR]   [1mmvn <args> -rf :appio-beans

**Comment by pperliti** [comment]
(solo come consiglio per i newbies come me) Sarebbe molto utile avere una spiegazione (anche solo di massima) della struttura del progetto (anche solo il primo livello di folder) e di eventuali osservazioni di cui tener conto quando si importa nei principali IDE (Eclipse, IntelliJ, ecc.). Il progetto è fatto bene ed è monumentale, per questo un breve vademecum su come orientarsi all'interno porterebbe ulteriore valore.
Grazie comunque.

**Comment by pperliti** [comment]
Ciao Lorenzo, 
ho capito che il mio errore (lo scrivo qui nel caso ricapiti in futuro a qualcun altro) è stato utilizzare Maven 3.9 (mentre la versione riportate nella documentazione è la 3.8). Compilando con Maven 3.8 si è risolto quasi tutto (a parte un piccolo errore legato a una MalformedURLException su AvvisoPagamento.jasper, risolto a mano).
Grazie per il supporto.
