### ISSUE TITLE
Autorizzazione stampa PT non visibile su avviso di pagamento

### ISSUE THREAD

**Issue by frdidonato** [link-it/govpay#624]
Salve, 
In riferimento alla issue #483  gentilmente si potrebbe capire come è stata risolta ? ho la versione 3.6.4 di GovPay e nonostante abbia messo il numero di autorizzazione sia sull'EC sia sul conto corrente Postale (Chekkato come Postale), nell'avviso in PDF, nella parte del bollettino postale, non vedo la sezione relativa al numero di autorizzazione nel bollettino.
Ho effettuato anche il reset della cache ma continuo a non vedere il numero di autorizzazione.

**Comment by frdidonato** [comment]
ho eppna effettuato anche un riavvia dell'applicativo ma nulla

**Comment by giuseppeformaro** [comment]
Ciao,
ho versioni maggiori ma mi pare di ricordare un problema simile anche a me nella 3.6. Prova a passare alla 3.7 dove ho provato e funziona.

**Comment by frdidonato** [comment]
@giuseppeformaro grazie mille per il supporto. Aggiornerò e ti farò sapere

**Comment by frdidonato** [comment]
sono passato alla 3.7.4 e la stampa avviene correttamente. Di contro non riesco più ad effettuare nessun pagamento. l'errore che ottengo è il seguente : 
it.govpay.core.exceptions.NdpException: it.govpay.core.exceptions.NotAuthorizedException: Operazione non autorizzata
        at it.govpay.web.ws.PagamentiTelematiciRTImpl.paaInviaRTImpl(PagamentiTelematiciRTImpl.java:370) ~[classes:?]
        at it.govpay.web.ws.PagamentiTelematiciRTImpl.paaInviaRT(PagamentiTelematiciRTImpl.java:234) ~[classes:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0]
        at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:179) ~[cxf-core-3.5.6.jar:3.5.6]
        at org.apache.cxf.jaxws.JAXWSMethodInvoker.performInvocation(JAXWSMethodInvoker.java:66) ~[cxf-rt-frontend-jaxws-3.5.6.jar:3.5.6]
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96) ~[cxf-core-3.5.6.jar:3.5.6]
        at org.apache.cxf.jaxws.AbstractJAXWSMethodInvoker.invoke(AbstractJAXWSMethodInvoker.java:232) ~[cxf-rt-frontend-jaxws-3.5.6.jar:3.5.6]
        at org.apache.cxf.jaxws.JAXWSMethodInvoker.invoke(JAXWSMethodInvoker.java:85) ~[cxf-rt-frontend-jaxws-3.5.6.jar:3.5.6]
        at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:74) ~[cxf-core-3.5.6.jar:3.5.6]
        at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59) ~[cxf-core-3.5.6.jar:3.5.6]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0]

**Comment by nardil** [comment]
Verifica di aver riportato eventuali modifiche alle configurazioni di spring-security delle api pagoPA all'interno dell'ear oppure, se l'installazione era stata perfezionata con tali file di configurazione in folder esterni, che questa impostazione sia stata mantenuta in fase di esecuzione dell'installer

**Comment by frdidonato** [comment]
risolto aggiornando alla 3.7.4 settando la configurazione con java 8 e wildfly 11
