### ISSUE TITLE
Errore inserimento dominio senza logo

### ISSUE THREAD

**Issue by SbGibson** [link-it/GovPay#65]
Versione 2.5.4
Inserendo un nuovo dominio senza inserire anche il logo non viene indicato che il logo è obbligatorio ma viene visualizzato un errore tipo "si è verificato un errore e riprovare piu tardi".

Nei log si trova questo errore:
```
Riscontrato errore durante l'esecuzione del metodo insert domini:it.govpay.web.rs.dars.exception.ConsoleException: net.sf.json.JSONException: JSONObject["logo"] is not a JSONArray.
it.govpay.web.rs.dars.exception.ConsoleException: it.govpay.web.rs.dars.exception.ConsoleException: net.sf.json.JSONException: JSONObject["logo"] is not a JSONArray.
at it.govpay.web.rs.dars.anagrafica.domini.DominiHandler.insert(DominiHandler.java:1141) ~[classes:?]
at it.govpay.web.rs.dars.base.DarsService.insert(DarsService.java:376) [classes:?]
Caused by: it.govpay.web.rs.dars.exception.ConsoleException: net.sf.json.JSONException: JSONObject["logo"] is not a JSONArray.
at it.govpay.web.rs.dars.anagrafica.domini.DominiHandler.creaDominioEAnagrafica(DominiHandler.java:1294) ~[classes:?]
at it.govpay.web.rs.dars.anagrafica.domini.DominiHandler.insert(DominiHandler.java:1082) ~[classes:?]
	... 48 more
Caused by: net.sf.json.JSONException: JSONObject["logo"] is not a JSONArray.
at net.sf.json.JSONObject.getJSONArray(JSONObject.java:2038) ~[json-lib-2.4-jdk15.jar:?]
at it.govpay.web.rs.dars.anagrafica.domini.DominiHandler.creaDominioEAnagrafica(DominiHandler.java:1231) ~[classes:?]
at it.govpay.web.rs.dars.anagrafica.domini.DominiHandler.insert(DominiHandler.java:1082) ~[classes:?]
	... 48 more
```

**Comment by nardil** [comment]
Ciao @SbGibson ,

l'errore e' stato risolto in 1b60fbfbb7babba9f9d84c0219a50cc11ed66259 ma non ancora rilasciato. Fammi sapere se hai problemi a compilare il branch 2.5.x per aggiornare la tua installazione.
