### ISSUE TITLE
Livello log errato per le eccezioni lanciate in fase di init del client di verifica pendenza 

### ISSUE THREAD

**Issue by pintorig** [link-it/govpay#667]
**Descrizione del Bug**
Modificare il livello di log per le eccezioni in fase di inizializzazione del client verifica pendenza.
Attualmente e' DEBUG, portarlo a ERROR

** Stacktrace **
``` bash
2023-12-21 12:15:33.840 | DEBUG | it.govpay.core.utils.VersamentoUtils:317 | ca77a70b-db56-4070-91cc-0c88c7c12332 | Aggiorno dal servizio applicativo dell'Ent
e: it.govpay.bd.model.applicazione@1ca56c8f[id=389,codapplicazione=pagogateway,connettoreintegrazione=it.govpay.model.connettore@2d7fcbea[idConnettore=pagogat
eway_INTEGRAZIONE,tipoAutenticazione=SSL,tipoSsl=SERVER,sslKsType=<null>,sslKsLocation=<null>,sslKsPasswd=<null>,sslPKeyPasswd=<null>,sslTsType=JKS,sslTsLocat
ion=/etc/pki/java/truststore_applicazioni.jks,sslTsPasswd=123456,sslType=TLSv1.2,httpUser=<null>,httpPassw=<null>,url=https://pago-api.optimia.it/api/PAGOCall
back/OptimiaPayProvider,urlServiziAvvisatura=<null>,azioneInUrl=false,subscriptionKeyValue=<null>,httpHeaderName=<null>,httpHeaderValue=<null>,apiKey=<null>,a
piId=<null>,oauth2ClientCredentialsClientId=<null>,oauth2ClientCredentialsClientSecret=<null>,oauth2ClientCredentialsUrlTokenEndpoint=<null>,oauth2ClientCrede
ntialsScope=<null>,versione=GP_REST_02],firmaRichiesta=NESSUNA,trusted=false,codApplicazioneIuv=<null>,regExp=.*,autoIuv=false,idUtenza=0]
2023-12-21 12:15:33.841 | DEBUG | it.govpay.core.utils.VersamentoUtils:327 | ca77a70b-db56-4070-91cc-0c88c7c12332 | Rilevata eccezione durante il processo di 
aggiornamento della pendenza, la proprieta' aggiornamentoValiditaMandatorio == false quindi verra' utilizzata la pendenza originale. Errore: java.io.FileNotFoundException: /etc/pki/java/truststore_applicazioni.jks (No such file or directory)
it.govpay.core.utils.client.exception.ClientException: java.io.FileNotFoundException: /etc/pki/java/truststore_applicazioni.jks (No such file or directory)
        at it.govpay.core.utils.client.BasicClientCORE.<init>(BasicClientCORE.java:319) ~[core-3.7.5.jar:?]
        at it.govpay.core.utils.client.BasicClientCORE.<init>(BasicClientCORE.java:199) ~[core-3.7.5.jar:?]
        at it.govpay.core.utils.client.VerificaClient.<init>(VerificaClient.java:95) ~[core-3.7.5.jar:?]
        at it.govpay.core.utils.VersamentoUtils.acquisisciVersamento(VersamentoUtils.java:380) ~[core-3.7.5.jar:?]
        at it.govpay.core.utils.VersamentoUtils.aggiornaVersamento(VersamentoUtils.java:318) ~[core-3.7.5.jar:?]
        at it.govpay.web.ws.PagamentiTelematiciCCPImpl.paVerifyPaymentNotice(PagamentiTelematiciCCPImpl.java:1236) ~[classes:?]
        at sun.reflect.GeneratedMethodAccessor776.invoke(Unknown Source) ~[?:?]
```

**Comment by nardil** [comment]
Verificare anche che venga registrato l'evento di verifica della pendenza come FAIL
